import type { Exercise } from '../../types'

const IMG_ARMS = 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop'
const IMG_GYM  = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const ARM_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // BÍCEPS (bicep)
  // ══════════════════════════════════════════

  {
    id: 'barbell_curl',
    name: 'Barbell Bicep Curl',
    nameEs: 'Curl de Bíceps con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    equipment: ['barbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.3,
    image: IMG_ARMS,
    instructions: [
      'De pie con barra en agarre supino al ancho de hombros. Codos pegados al cuerpo.',
      'Curva los antebrazos hacia los hombros apretando el bíceps al máximo.',
      'Baja con control en 2-3 segundos. No balancees el torso.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Bicep Curl',
    nameEs: 'Curl de Bíceps con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_ARMS,
    instructions: [
      'De pie con mancuernas a los lados. Codos pegados al cuerpo.',
      'Curva los brazos supinando la muñeca al subir (palma hacia arriba al final).',
      'Baja con control. Alterna o ambos brazos simultáneamente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    nameEs: 'Curl Martillo',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_ARMS,
    instructions: [
      'Mancuernas con agarre neutro (palmas enfrentadas). Posición de martillo.',
      'Curva los brazos manteniendo el agarre neutro. Activa el braquial.',
      'Baja con control. Trabaja el braquial y braquirradial además del bíceps.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    nameEs: 'Curl en Predicador',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['barbell', 'machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Apoya los brazos en el pad del predicador. Barra o mancuerna en manos.',
      'Baja los brazos hasta extensión casi completa. No hiperextiendas.',
      'Curva apretando el bíceps al máximo. Mayor aislamiento por la fijación.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    nameEs: 'Curl en Polea',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Polea baja con barra recta o EZ. Codos pegados al cuerpo.',
      'Curva los brazos manteniendo tensión constante de la polea.',
      'La polea mantiene más tensión en la posición baja vs. mancuernas.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    nameEs: 'Curl Inclinado con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'isolation', compoundBonus: 1.2,
    image: IMG_ARMS,
    instructions: [
      'Banco inclinado a 45-60°. Brazos colgando rectos hacia abajo.',
      'Curva los brazos supinando la muñeca. Mayor estiramiento del bíceps largo.',
      'Baja completamente. La posición inclinada maximiza el rango de estiramiento.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    nameEs: 'Curl de Concentración',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_ARMS,
    instructions: [
      'Sentado, codo apoyado en el interior del muslo. Mancuerna colgando.',
      'Curva el brazo girando la muñeca. Máxima contracción arriba.',
      'Baja con control. Excelente pico de bíceps.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15 c/u', intermediate: '10-12 c/u', advanced: '10-12 c/u' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'machine_curl',
    name: 'Machine Curl',
    nameEs: 'Curl en Máquina',
    muscleGroup: 'upperBody', muscleTarget: 'bicep',
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento para que los codos queden alineados con el pivote.',
      'Curva los brazos hasta la contracción máxima. Pausa 1 segundo.',
      'Baja con control. Ideal para sobrecarga progresiva con control.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // TRÍCEPS (tricep)
  // ══════════════════════════════════════════

  {
    id: 'tricep_dip_bench',
    name: 'Bench Dip',
    nameEs: 'Fondos en Banco para Tríceps',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: ['shoulders'],
    equipment: ['bench', 'bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.5,
    image: IMG_ARMS,
    instructions: [
      'Manos en el borde del banco, pies extendidos al frente.',
      'Baja el cuerpo flexionando codos hasta 90°. Mantenlos hacia atrás.',
      'Empuja hacia arriba extendiendo los codos. No bloquees completamente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'close_grip_bench_press',
    name: 'Close Grip Bench Press',
    nameEs: 'Press de Banca Agarre Cerrado',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.8,
    image: IMG_ARMS,
    instructions: [
      'Agarra la barra algo más estrecho que los hombros. No demasiado cerrado.',
      'Baja la barra al pecho con codos pegados al cuerpo (45°).',
      'Empuja explosivamente. Activa principalmente los tríceps.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '8-10', intermediate: '6-10', advanced: '6-8' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'tricep_pushdown_cable',
    name: 'Tricep Pushdown',
    nameEs: 'Extensión de Tríceps en Polea',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Polea alta. Agarra la barra o cuerda con codos pegados al cuerpo.',
      'Extiende los brazos hacia abajo hasta extensión completa. Aprieta el tríceps.',
      'Regresa con control hasta codos a 90°. No muevas los codos.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'skullcrusher',
    name: 'Skull Crusher',
    nameEs: 'Rompecráneos con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'isolation', compoundBonus: 1.3,
    image: IMG_ARMS,
    instructions: [
      'Acuéstate en banco. Brazos extendidos sobre el pecho sosteniendo la barra.',
      'Flexiona los codos bajando la barra hacia la frente. Codos fijos.',
      'Extiende los codos regresando arriba. Máximo aislamiento del tríceps.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'overhead_tricep_dumbbell',
    name: 'Overhead Tricep Extension',
    nameEs: 'Extensión de Tríceps sobre la Cabeza',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_ARMS,
    instructions: [
      'Sentado o de pie. Sostén la mancuerna sobre la cabeza con ambas manos.',
      'Baja la mancuerna detrás de la cabeza flexionando los codos. Codos fijos.',
      'Extiende los codos hacia arriba apretando el tríceps. Mayor activación de la cabeza larga.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'tricep_kickback',
    name: 'Tricep Kickback',
    nameEs: 'Extensión de Tríceps en Patada',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_ARMS,
    instructions: [
      'Inclina el torso a 45-90°. Codo fijo al lado del cuerpo a 90°.',
      'Extiende el brazo hacia atrás hasta extensión completa del codo.',
      'Regresa con control. Mantén el codo fijo durante todo el movimiento.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15 c/u', intermediate: '12-15 c/u', advanced: '12-15 c/u' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push Up',
    nameEs: 'Flexión Diamante',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: ['chest'],
    equipment: ['bodyweight'], difficulty: 2, type: 'compound', compoundBonus: 1.5,
    image: IMG_ARMS,
    instructions: [
      'Manos formando un triángulo (diamante) bajo el pecho. Pulgares e índices se tocan.',
      'Baja el pecho hacia las manos manteniendo los codos cerca del cuerpo.',
      'Empuja hacia arriba apretando los tríceps. Mayor activación que push up normal.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '6-10', intermediate: '10-15', advanced: '15-20' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'cable_overhead_tricep',
    name: 'Cable Overhead Tricep Extension',
    nameEs: 'Extensión de Tríceps sobre la Cabeza en Polea',
    muscleGroup: 'upperBody', muscleTarget: 'tricep',
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_GYM,
    instructions: [
      'Polea alta con cuerda. De espaldas a la máquina, inclínate ligeramente.',
      'Lleva la cuerda hacia adelante extendiendo los codos frente a ti.',
      'Regresa con control. La polea mantiene tensión en el estiramiento.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // ANTEBRAZOS (forearm)
  // ══════════════════════════════════════════

  {
    id: 'wrist_curl_dumbbell',
    name: 'Wrist Curl',
    nameEs: 'Curl de Muñeca con Mancuerna',
    muscleGroup: 'upperBody', muscleTarget: 'forearm',
    primaryMuscles: ['forearms'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_ARMS,
    instructions: [
      'Sentado, antebrazo sobre el muslo con la muñeca fuera del borde. Palma arriba.',
      'Baja la mancuerna arqueando la muñeca hacia abajo.',
      'Sube apretando los flexores del antebrazo al máximo.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'reverse_wrist_curl',
    name: 'Reverse Wrist Curl',
    nameEs: 'Curl Inverso de Muñeca',
    muscleGroup: 'upperBody', muscleTarget: 'forearm',
    primaryMuscles: ['forearms'], secondaryMuscles: [],
    equipment: ['barbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_ARMS,
    instructions: [
      'Antebrazo sobre el muslo, palma hacia abajo. Barra o mancuerna en mano.',
      'Extiende la muñeca hacia arriba. Trabaja los extensores del antebrazo.',
      'Baja con control. Complementa el curl de muñeca regular.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'farmer_carry',
    name: 'Farmer Carry',
    nameEs: 'Caminata del Granjero',
    muscleGroup: 'upperBody', muscleTarget: 'forearm',
    primaryMuscles: ['forearms'], secondaryMuscles: ['shoulders', 'core', 'back'],
    equipment: ['dumbbell'], difficulty: 1, type: 'compound', compoundBonus: 1.4,
    image: IMG_ARMS,
    instructions: [
      'Sostén mancuernas pesadas a los lados. Torso erguido, hombros atrás.',
      'Camina a paso controlado por 20-40 metros.',
      'Desarrolla fuerza de agarre y resistencia del antebrazo funcionalmente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '20m', intermediate: '30m', advanced: '40m' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
]
