import type { Exercise } from '../../types'

const IMG_BACK = 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop'
const IMG_GYM  = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const BACK_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // DORSALES / LATS (back_lats)
  // ══════════════════════════════════════════

  {
    id: 'pull_up',
    name: 'Pull Up',
    nameEs: 'Dominadas',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['pullup_bar', 'bodyweight'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_BACK,
    instructions: [
      'Agarra la barra con las palmas hacia afuera, más ancho que los hombros.',
      'Tira hacia arriba llevando el pecho a la barra. Activa los dorsales.',
      'Baja de forma controlada hasta extender completamente los brazos.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '3-6', intermediate: '6-10', advanced: '8-12' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'chin_up',
    name: 'Chin Up',
    nameEs: 'Dominadas Supinas',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['pullup_bar', 'bodyweight'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_BACK,
    instructions: [
      'Agarra la barra con palmas hacia ti (supino) al ancho de hombros.',
      'Tira hacia arriba llevando el mentón sobre la barra. Codos hacia abajo.',
      'Baja con control hasta extensión completa. Mayor activación de bíceps.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '4-6', intermediate: '6-10', advanced: '8-12' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'lat_pulldown_wide',
    name: 'Wide Grip Lat Pulldown',
    nameEs: 'Jalón al Pecho Agarre Ancho',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['machine', 'cable'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_GYM,
    instructions: [
      'Siéntate con las rodillas bajo el rodillo. Agarra la barra más ancha que los hombros.',
      'Jala la barra hacia el pecho superior apretando los dorsales al final.',
      'Regresa lentamente hasta extensión completa. No balancees el torso.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'lat_pulldown_neutral',
    name: 'Neutral Grip Lat Pulldown',
    nameEs: 'Jalón Agarre Neutro',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['machine', 'cable'], difficulty: 1, type: 'compound', compoundBonus: 1.7,
    image: IMG_GYM,
    instructions: [
      'Usa una barra con agarre neutro (palmas enfrentadas) al ancho de hombros.',
      'Jala hacia abajo llevando las manos a los lados del pecho.',
      'Aprieta los dorsales en la posición baja y regresa con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'single_arm_dumbbell_row',
    name: 'Single Arm Dumbbell Row',
    nameEs: 'Remo con Mancuerna a Una Mano',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_BACK,
    instructions: [
      'Apoya una mano y rodilla en el banco. Espalda paralela al suelo.',
      'Jala la mancuerna hacia la cadera llevando el codo hacia atrás y arriba.',
      'Aprieta el dorsal en la parte alta y baja con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight Arm Pulldown',
    nameEs: 'Jalón de Dorsal con Brazos Rectos',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 2, type: 'isolation', compoundBonus: 1.3,
    image: IMG_GYM,
    instructions: [
      'De pie frente a la polea alta. Agarra la barra con brazos casi extendidos.',
      'Lleva la barra hacia abajo hasta las caderas manteniendo los brazos rectos.',
      'Aprieta los dorsales y regresa lentamente. Excelente aislamiento.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'dumbbell_pullover',
    name: 'Dumbbell Pullover',
    nameEs: 'Pullover con Mancuerna',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['chest'],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'isolation', compoundBonus: 1.4,
    image: IMG_BACK,
    instructions: [
      'Acuéstate transversal en el banco. Solo la parte alta de la espalda apoyada.',
      'Sostén la mancuerna con ambas manos sobre el pecho, brazos semi-extendidos.',
      'Baja la mancuerna hacia atrás de la cabeza en arco. Regresa apretando dorsal.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'assisted_pull_up',
    name: 'Assisted Pull Up',
    nameEs: 'Dominadas Asistidas',
    muscleGroup: 'upperBody', muscleTarget: 'back_lats',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['machine'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_GYM,
    instructions: [
      'Ajusta el peso de asistencia. Más peso = menos dificultad.',
      'Tira hacia arriba llevando el pecho a la barra, codos abajo y atrás.',
      'Baja lentamente hasta extensión completa. Reduce asistencia progresivamente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-12', intermediate: '8-12', advanced: '10-15' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // ESPALDA ALTA (back_upper)
  // ══════════════════════════════════════════

  {
    id: 'barbell_row',
    name: 'Barbell Bent Over Row',
    nameEs: 'Remo con Barra Inclinado',
    muscleGroup: 'upperBody', muscleTarget: 'back_upper',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_BACK,
    instructions: [
      'Inclina el torso a 45° con la barra colgando. Espalda recta y neutral.',
      'Jala la barra hacia el ombligo apretando la espalda al final del recorrido.',
      'Baja con control hasta brazos extendidos. Mantén la espalda recta en todo momento.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '8-10', intermediate: '6-10', advanced: '5-8' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    nameEs: 'Remo en Polea Sentado',
    muscleGroup: 'upperBody', muscleTarget: 'back_upper',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'], difficulty: 1, type: 'compound', compoundBonus: 1.7,
    image: IMG_GYM,
    instructions: [
      'Siéntate con pies en el soporte, espalda recta y ligera inclinación adelante.',
      'Jala el mango hacia el abdomen llevando los codos atrás y apretando la espalda.',
      'Regresa con control hasta brazos extendidos. No te balancees.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    nameEs: 'Face Pull con Polea',
    muscleGroup: 'upperBody', muscleTarget: 'back_upper',
    primaryMuscles: ['back'], secondaryMuscles: ['shoulders'],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_GYM,
    instructions: [
      'Polea a la altura de los ojos. Usa la cuerda con agarre neutro.',
      'Jala hacia la cara separando las manos y llevando los codos hacia afuera.',
      'Aprieta los romboides y deltoides posteriores al final. Regresa con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'barbell_shrug',
    name: 'Barbell Shrug',
    nameEs: 'Encogimientos con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'back_upper',
    primaryMuscles: ['back'], secondaryMuscles: [],
    equipment: ['barbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_BACK,
    instructions: [
      'De pie con la barra en agarre prono al frente. Brazos extendidos.',
      'Eleva los hombros hacia las orejas lo más alto posible. Aprieta 1 segundo.',
      'Baja lentamente. No hagas círculos con los hombros, solo movimiento vertical.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'dumbbell_shrug',
    name: 'Dumbbell Shrug',
    nameEs: 'Encogimientos con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'back_upper',
    primaryMuscles: ['back'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_BACK,
    instructions: [
      'De pie con mancuernas a los lados. Mayor rango de movimiento que con barra.',
      'Eleva los hombros lo más alto posible. Pausa 1-2 segundos arriba.',
      'Baja de forma controlada. Permite mayor amplitud de movimiento.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // ESPALDA MEDIA / ROMBOIDES (back_mid)
  // ══════════════════════════════════════════

  {
    id: 'chest_supported_row',
    name: 'Chest Supported Dumbbell Row',
    nameEs: 'Remo con Mancuernas en Banco Inclinado',
    muscleGroup: 'upperBody', muscleTarget: 'back_mid',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_BACK,
    instructions: [
      'Recuéstate boca abajo en banco inclinado a 45°. Mancuernas colgando.',
      'Jala las mancuernas hacia arriba llevando los codos al techo.',
      'Aprieta los romboides y la espalda media. Baja con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'machine_row_chest',
    name: 'Machine Chest Supported Row',
    nameEs: 'Remo en Máquina con Soporte de Pecho',
    muscleGroup: 'upperBody', muscleTarget: 'back_mid',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['machine'], difficulty: 1, type: 'compound', compoundBonus: 1.5,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento y el pecho contra el soporte. Agarra las asas.',
      'Jala hacia atrás llevando los codos al máximo recorrido.',
      'Aprieta la espalda media y regresa con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'cable_row_wide',
    name: 'Wide Grip Cable Row',
    nameEs: 'Remo en Polea Agarre Ancho',
    muscleGroup: 'upperBody', muscleTarget: 'back_mid',
    primaryMuscles: ['back'], secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'], difficulty: 2, type: 'compound', compoundBonus: 1.6,
    image: IMG_GYM,
    instructions: [
      'Usa barra larga en la polea baja. Agarre prono más ancho que los hombros.',
      'Jala hacia el abdomen llevando los codos al lado del cuerpo.',
      'Activa romboides y espalda media apretando en la posición final.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // ESPALDA BAJA (back_lower)
  // ══════════════════════════════════════════

  {
    id: 'deadlift_conventional',
    name: 'Conventional Deadlift',
    nameEs: 'Peso Muerto Convencional',
    muscleGroup: 'upperBody', muscleTarget: 'back_lower',
    primaryMuscles: ['back'], secondaryMuscles: ['glutes', 'hamstrings', 'quads'],
    equipment: ['barbell'], difficulty: 3, type: 'compound', compoundBonus: 2.0,
    image: IMG_BACK,
    instructions: [
      'Barra sobre los empeines. Cadera hacia atrás, espalda recta, agarre al ancho de caderas.',
      'Empuja el suelo alejándolo y estira las caderas hacia adelante al subir.',
      'Baja controlado: caderas atrás primero, luego dobla las rodillas al llegar a las tibias.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '5-6', intermediate: '4-6', advanced: '3-5' },
    rest: { beginner: 180, intermediate: 150, advanced: 120 },
  },
  {
    id: 'hyperextension',
    name: 'Hyperextension',
    nameEs: 'Hiperextensión de Espalda',
    muscleGroup: 'upperBody', muscleTarget: 'back_lower',
    primaryMuscles: ['back'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.3,
    image: IMG_GYM,
    instructions: [
      'Posiciona las caderas en el borde del banco de hiperextensiones. Pies asegurados.',
      'Baja el torso hacia el suelo manteniendo la espalda recta (no arqueada).',
      'Levanta el torso hasta que quede en línea con las piernas. Aprieta los glúteos arriba.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-15', intermediate: '10-15', advanced: '12-20' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    nameEs: 'Buenos Días con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'back_lower',
    primaryMuscles: ['back'], secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 1.7,
    image: IMG_BACK,
    instructions: [
      'Barra en la nuca. De pie con rodillas ligeramente flexionadas.',
      'Inclina el torso hacia adelante empujando las caderas hacia atrás.',
      'Regresa a posición erguida apretando glúteos e isquiotibiales.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 75 },
  },
  {
    id: 'back_extension_machine',
    name: 'Back Extension Machine',
    nameEs: 'Extensión de Espalda en Máquina',
    muscleGroup: 'upperBody', muscleTarget: 'back_lower',
    primaryMuscles: ['back'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_GYM,
    instructions: [
      'Ajusta la máquina al tamaño de tu torso. Siéntate con espalda recta.',
      'Empuja contra el soporte extendiendo la espalda hacia atrás.',
      'Regresa con control a la posición inicial sin dejar caer el peso.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'superman',
    name: 'Superman',
    nameEs: 'Superman',
    muscleGroup: 'upperBody', muscleTarget: 'back_lower',
    primaryMuscles: ['back'], secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Boca abajo en el suelo con brazos extendidos al frente.',
      'Eleva simultáneamente brazos, pecho y piernas del suelo. Pausa 2 segundos.',
      'Baja con control. Excelente para activación lumbar sin carga.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '10-12', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
]
