import type { Exercise } from '../../types'

const IMG_CHEST = 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop'
const IMG_GYM   = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const CHEST_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // PECHO SUPERIOR (chest_upper)
  // ══════════════════════════════════════════

  {
    id: 'incline_press_barbell',
    name: 'Incline Barbell Bench Press',
    nameEs: 'Press Inclinado con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_CHEST,
    instructions: [
      'Ajusta el banco entre 30-45°. Agarra la barra a una anchura mayor que los hombros.',
      'Baja la barra hasta la clavícula de forma controlada (2-3 seg).',
      'Empuja hacia arriba y ligeramente hacia atrás hasta extender los codos.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '6-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'incline_press_dumbbell',
    name: 'Incline Dumbbell Press',
    nameEs: 'Press Inclinado con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_CHEST,
    instructions: [
      'Banco a 30-45°. Sostén las mancuernas a la altura del pecho con codos a 75°.',
      'Empuja hacia arriba y adentro hasta que las mancuernas casi se toquen.',
      'Baja con control en 2-3 segundos manteniendo tensión en el pecho.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'incline_press_smith',
    name: 'Incline Smith Machine Press',
    nameEs: 'Press Inclinado en Máquina Smith',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['machine', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_GYM,
    instructions: [
      'Coloca el banco inclinado bajo la barra Smith. Ajusta el agarre a anchura de hombros.',
      'Desbloquea la barra y bájala hasta la parte superior del pecho.',
      'Empuja hacia arriba de forma explosiva hasta casi extender los codos.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '8-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'incline_fly_dumbbell',
    name: 'Incline Dumbbell Fly',
    nameEs: 'Aperturas Inclinadas con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'isolation', compoundBonus: 1.2,
    image: IMG_CHEST,
    instructions: [
      'Banco a 30°. Sostén mancuernas con brazos semi-extendidos encima del pecho.',
      'Abre los brazos en arco amplio bajando hasta sentir estiramiento en el pecho.',
      'Cierra los brazos como si abrazaras un árbol grande. No bloquees los codos.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'cable_fly_low_to_high',
    name: 'Cable Crossover Low to High',
    nameEs: 'Cruce de Poleas Bajo hacia Alto',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 2, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Poleas en posición baja. De pie en el centro, un pie adelante.',
      'Lleva los cables hacia arriba y al frente, cruzando las manos a la altura del pecho.',
      'Regresa lentamente al punto inicial manteniendo tensión constante.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'pec_deck_upper',
    name: 'Pec Deck (Upper Focus)',
    nameEs: 'Contractora de Pecho Superior',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento para que los codos queden a la altura de los hombros o ligeramente por debajo.',
      'Cierra los brazos hasta el centro apretando el pecho al final del recorrido.',
      'Regresa con control sin soltar la tensión muscular.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'push_up_feet_elevated',
    name: 'Feet Elevated Push Up',
    nameEs: 'Flexión con Pies Elevados',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['bodyweight', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.5,
    image: IMG_CHEST,
    instructions: [
      'Coloca los pies sobre un banco o superficie elevada. Manos al ancho de hombros en el suelo.',
      'Baja el pecho hacia el suelo manteniendo el cuerpo recto.',
      'Empuja hacia arriba de forma explosiva. El ángulo activa el pecho superior.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-10', intermediate: '10-15', advanced: '15-20' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'hammer_strength_incline',
    name: 'Hammer Strength Incline Press',
    nameEs: 'Press Inclinado Hammer Strength',
    muscleGroup: 'upperBody', muscleTarget: 'chest_upper',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['machine'], difficulty: 2, type: 'compound', compoundBonus: 1.7,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento para que las asas queden a la altura del pecho superior.',
      'Empuja las asas hacia arriba y al frente hasta casi extender los codos.',
      'Regresa con control manteniendo los omóplatos juntos contra el respaldo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // PECHO MEDIO (chest_mid)
  // ══════════════════════════════════════════

  {
    id: 'bench_press_barbell',
    name: 'Barbell Bench Press',
    nameEs: 'Press de Banca con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_CHEST,
    instructions: [
      'Acuéstate en el banco con los pies apoyados en el suelo. Arco natural en la espalda baja.',
      'Agarra la barra a una anchura mayor que los hombros. Retrae los omóplatos.',
      'Baja la barra hasta el pecho medio de forma controlada y empuja explosivamente hacia arriba.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '5' },
    reps: { beginner: '8-10', intermediate: '8-12', advanced: '6-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'bench_press_dumbbell',
    name: 'Dumbbell Bench Press',
    nameEs: 'Press de Banca con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_CHEST,
    instructions: [
      'Acuéstate con mancuernas a la altura del pecho, codos a 75° del cuerpo.',
      'Empuja hacia arriba y adentro hasta que las mancuernas casi se toquen arriba.',
      'Baja con control en 2-3 segundos hasta sentir estiramiento en el pecho.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'bench_press_smith',
    name: 'Smith Machine Bench Press',
    nameEs: 'Press de Banca en Máquina Smith',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['machine', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_GYM,
    instructions: [
      'Coloca el banco plano bajo la barra Smith. Agarre al ancho de hombros.',
      'Baja la barra al pecho de forma controlada. La máquina guía el movimiento.',
      'Empuja hasta casi extender los codos. No bloquees completamente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '8-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'dumbbell_fly_flat',
    name: 'Flat Dumbbell Fly',
    nameEs: 'Aperturas con Mancuernas en Banco Plano',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'isolation', compoundBonus: 1.2,
    image: IMG_CHEST,
    instructions: [
      'Acuéstate en banco plano con mancuernas extendidas sobre el pecho.',
      'Abre los brazos en arco amplio bajando hasta sentir estiramiento completo.',
      'Cierra los brazos como si abrazaras un barril. Aprieta el pecho arriba.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'cable_fly_mid',
    name: 'Cable Fly Mid',
    nameEs: 'Cruce de Poleas Medio',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 2, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Poleas a la altura de los hombros. De pie en el centro con un pie adelante.',
      'Lleva los cables al frente cruzando las manos a la altura del ombligo.',
      'Regresa lentamente controlando la apertura sin perder tensión en el pecho.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'pec_deck_flat',
    name: 'Pec Deck Machine',
    nameEs: 'Contractora de Pecho',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Siéntate con la espalda recta contra el respaldo. Ajusta el asiento.',
      'Cierra los brazos hasta el centro apretando el pecho en el punto máximo.',
      'Regresa con control sin dejar caer el peso. Mantén tensión constante.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '10-12' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'push_up_standard',
    name: 'Standard Push Up',
    nameEs: 'Flexión de Brazos Estándar',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.5,
    image: IMG_CHEST,
    instructions: [
      'Posición de plancha alta, manos al ancho de hombros. Cuerpo recto de cabeza a talones.',
      'Baja el pecho al suelo manteniendo los codos a 45° del cuerpo.',
      'Empuja hacia arriba de forma explosiva. Aprieta el pecho arriba.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-12', intermediate: '12-20', advanced: '20-30' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'push_up_wide',
    name: 'Wide Grip Push Up',
    nameEs: 'Flexión con Agarre Ancho',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.4,
    image: IMG_CHEST,
    instructions: [
      'Manos significativamente más anchas que los hombros. Dedos apuntando hacia afuera.',
      'Baja el pecho entre las manos sintiendo el estiramiento en el pecho.',
      'Empuja hacia arriba apretando el pecho en la posición alta.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-12', intermediate: '12-20', advanced: '20-30' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'hammer_strength_flat',
    name: 'Hammer Strength Flat Press',
    nameEs: 'Press Plano Hammer Strength',
    muscleGroup: 'upperBody', muscleTarget: 'chest_mid',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['machine'], difficulty: 2, type: 'compound', compoundBonus: 1.7,
    image: IMG_GYM,
    instructions: [
      'Siéntate con la espalda apoyada. Agarra las asas a la altura del pecho medio.',
      'Empuja hacia adelante hasta casi extender los codos. Aprieta el pecho.',
      'Regresa con control hasta sentir estiramiento completo en el pecho.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // PECHO INFERIOR (chest_lower)
  // ══════════════════════════════════════════

  {
    id: 'decline_press_barbell',
    name: 'Decline Barbell Press',
    nameEs: 'Press Declinado con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_CHEST,
    instructions: [
      'Banco declinado a -15 a -30°. Asegura los pies. Agarre al ancho de hombros.',
      'Baja la barra hasta el pecho inferior de forma controlada.',
      'Empuja hacia arriba y ligeramente hacia la cabeza hasta extender los codos.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '6-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'decline_press_dumbbell',
    name: 'Decline Dumbbell Press',
    nameEs: 'Press Declinado con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.7,
    image: IMG_CHEST,
    instructions: [
      'Banco declinado. Sostén las mancuernas a la altura del pecho inferior.',
      'Empuja hacia arriba y ligeramente adentro hasta casi tocar las mancuernas.',
      'Baja con control en 2-3 segundos hasta el estiramiento máximo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'chest_dip',
    name: 'Chest Dip',
    nameEs: 'Fondos en Barras (Pecho)',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_CHEST,
    instructions: [
      'Agarra las barras paralelas. Inclina el torso hacia adelante (30-45°).',
      'Baja el cuerpo hasta que los codos formen 90°, sintiendo estiramiento en el pecho.',
      'Empuja hacia arriba usando el pecho inferior. Mantén la inclinación hacia adelante.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '6-8', intermediate: '8-12', advanced: '12-15' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'cable_fly_high_to_low',
    name: 'Cable Crossover High to Low',
    nameEs: 'Cruce de Poleas Alto hacia Bajo',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 2, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Poleas en posición alta. De pie en el centro, un pie adelante para estabilidad.',
      'Lleva los cables hacia abajo y al frente, cruzando las manos a la altura de las caderas.',
      'Regresa lentamente al punto inicial controlando la apertura.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'push_up_decline',
    name: 'Decline Push Up',
    nameEs: 'Flexión Declinada',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.4,
    image: IMG_CHEST,
    instructions: [
      'Manos en el suelo al ancho de hombros. Pies elevados en una silla o banco.',
      'Baja el pecho hacia el suelo manteniendo el cuerpo recto.',
      'Empuja hacia arriba de forma explosiva. Activa el pecho inferior.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-12', intermediate: '12-20', advanced: '20-30' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'dip_assisted',
    name: 'Assisted Dip Machine',
    nameEs: 'Fondos Asistidos en Máquina',
    muscleGroup: 'upperBody', muscleTarget: 'chest_lower',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps'],
    equipment: ['machine'], difficulty: 1, type: 'compound', compoundBonus: 1.5,
    image: IMG_GYM,
    instructions: [
      'Selecciona el peso de asistencia. A mayor asistencia, menor dificultad.',
      'Inclina el torso hacia adelante para activar más el pecho.',
      'Baja hasta 90° de flexión de codo, luego empuja hacia arriba.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '12-15' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
]
