import type { Exercise } from '../../types'

const IMG_CORE = 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop'
const IMG_GYM  = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const CORE_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // ABDOMEN / ABS (abs)
  // ══════════════════════════════════════════

  {
    id: 'crunch',
    name: 'Crunch',
    nameEs: 'Crunch Abdominal',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_CORE,
    instructions: [
      'Acuéstate boca arriba. Rodillas flexionadas, pies apoyados. Manos en la nuca.',
      'Eleva solo los hombros del suelo apretando el abdomen. No jales el cuello.',
      'Baja con control sin que la cabeza toque el suelo entre repeticiones.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '20-25', advanced: '25-30' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    nameEs: 'Crunch en Polea',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Arrodíllate frente a la polea alta. Agarra la cuerda detrás de la cabeza.',
      'Flexiona el torso hacia abajo apretando el abdomen. Caderas fijas.',
      'Regresa con control. Permite sobrecarga progresiva a diferencia del crunch normal.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    nameEs: 'Elevación de Piernas Colgado',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['pullup_bar', 'bodyweight'], difficulty: 2, type: 'isolation', compoundBonus: 1.4,
    image: IMG_CORE,
    instructions: [
      'Cuelga de la barra con agarre prono. Evita balancearte.',
      'Eleva las piernas hasta que queden paralelas al suelo (o más). Aprieta el abdomen.',
      'Baja con control. Curvea la pelvis al subir para mayor activación abdominal.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-10', intermediate: '10-12', advanced: '12-15' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'plank',
    name: 'Plank',
    nameEs: 'Plancha Abdominal',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_CORE,
    instructions: [
      'Posición de plancha sobre antebrazos. Cuerpo recto de cabeza a talones.',
      'Aprieta abdomen, glúteos y cuádriceps. No dejes caer la cadera.',
      'Mantén la posición el tiempo objetivo. Respira normalmente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '20-30 seg', intermediate: '30-60 seg', advanced: '60-90 seg' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    nameEs: 'Rodillo Abdominal',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: ['back', 'shoulders'],
    equipment: ['bodyweight'], difficulty: 3, type: 'compound', compoundBonus: 1.6,
    image: IMG_CORE,
    instructions: [
      'Arrodíllado con el rodillo bajo los hombros. Espalda recta.',
      'Extiende el cuerpo hacia adelante rodando lentamente. Abdomen activado.',
      'Regresa jalando con el abdomen. Uno de los mejores ejercicios de core.',
    ],
    sets: { beginner: '2-3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '5-8', intermediate: '8-12', advanced: '12-15' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'sit_up',
    name: 'Sit Up',
    nameEs: 'Abdominales Completos',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_CORE,
    instructions: [
      'Acuéstate boca arriba con rodillas flexionadas. Manos cruzadas en el pecho.',
      'Sube el torso hasta quedar sentado usando el abdomen. No el cuello.',
      'Baja con control hasta que la espalda casi toque el suelo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '20-25', advanced: '25-30' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'v_up',
    name: 'V-Up',
    nameEs: 'Elevación en V',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'], difficulty: 2, type: 'isolation', compoundBonus: 1.3,
    image: IMG_CORE,
    instructions: [
      'Acuéstate con brazos extendidos sobre la cabeza y piernas rectas.',
      'Eleva simultáneamente el torso y las piernas formando una "V".',
      'Baja con control sin que piernas ni brazos toquen el suelo entre reps.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-12', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'machine_crunch',
    name: 'Machine Crunch',
    nameEs: 'Crunch en Máquina',
    muscleGroup: 'core', muscleTarget: 'abs',
    primaryMuscles: ['abs'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta los pads a la altura del pecho. Siéntate con pies asegurados.',
      'Flexiona el torso hacia adelante apretando el abdomen al máximo.',
      'Regresa con control. Permite sobrecarga progresiva constante.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // OBLICUOS (obliques)
  // ══════════════════════════════════════════

  {
    id: 'russian_twist',
    name: 'Russian Twist',
    nameEs: 'Giro Ruso',
    muscleGroup: 'core', muscleTarget: 'obliques',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_CORE,
    instructions: [
      'Sentado con torso a 45°, pies elevados. Manos juntas frente al pecho.',
      'Gira el torso de lado a lado tocando el suelo junto a las caderas.',
      'Para más difícil: sostén un disco o mancuerna. Mantén el pecho alto.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '20 (10c/u)', intermediate: '30 (15c/u)', advanced: '40 (20c/u)' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'side_plank',
    name: 'Side Plank',
    nameEs: 'Plancha Lateral',
    muscleGroup: 'core', muscleTarget: 'obliques',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abs', 'glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_CORE,
    instructions: [
      'Apoya un antebrazo en el suelo. Cuerpo en línea recta lateral.',
      'Eleva las caderas del suelo. Aprieta oblicuos y glúteos.',
      'Mantén la posición. Cambia de lado después del tiempo objetivo.',
    ],
    sets: { beginner: '3 c/u', intermediate: '3-4 c/u', advanced: '4 c/u' },
    reps: { beginner: '20-30 seg', intermediate: '30-45 seg', advanced: '45-60 seg' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'cable_woodchop',
    name: 'Cable Woodchop',
    nameEs: 'Leñador en Polea',
    muscleGroup: 'core', muscleTarget: 'obliques',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abs', 'shoulders'],
    equipment: ['cable'], difficulty: 2, type: 'compound', compoundBonus: 1.3,
    image: IMG_GYM,
    instructions: [
      'Polea alta al costado. Agarra el mango con ambas manos. Pies al ancho de hombros.',
      'Gira el torso jalando la polea hacia abajo y al frente en diagonal.',
      'Regresa controlado a la posición inicial. Trabaja la cadena de rotación.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12 c/u', intermediate: '12-15 c/u', advanced: '12-15 c/u' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'oblique_crunch',
    name: 'Oblique Crunch',
    nameEs: 'Crunch Oblicuo',
    muscleGroup: 'core', muscleTarget: 'obliques',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_CORE,
    instructions: [
      'Acuéstate con rodillas a un lado (o cruza una pierna). Manos en la nuca.',
      'Eleva el hombro opuesto hacia las rodillas rotando el torso.',
      'Siente la contracción en el oblicuo. Baja con control y cambia de lado.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15 c/u', intermediate: '15-20 c/u', advanced: '20-25 c/u' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    nameEs: 'Crunch de Bicicleta',
    muscleGroup: 'core', muscleTarget: 'obliques',
    primaryMuscles: ['obliques'], secondaryMuscles: ['abs'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_CORE,
    instructions: [
      'Acuéstate boca arriba. Manos en la nuca, piernas levantadas a 45°.',
      'Lleva el codo derecho hacia la rodilla izquierda y viceversa alternando.',
      'Mueve las piernas simulando el pedaleo. Activación alta de oblicuos.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '20 (10c/u)', intermediate: '30 (15c/u)', advanced: '40 (20c/u)' },
    rest: { beginner: 60, intermediate: 45, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // LUMBAR (lower_back)
  // ══════════════════════════════════════════

  {
    id: 'hyperextension_back',
    name: 'Hyperextension',
    nameEs: 'Hiperextensión Lumbar',
    muscleGroup: 'core', muscleTarget: 'lower_back',
    primaryMuscles: ['lower_back'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.3,
    image: IMG_GYM,
    instructions: [
      'Posiciona las caderas en el borde del banco GHD. Pies asegurados.',
      'Baja el torso hacia el suelo manteniendo la espalda neutra.',
      'Eleva hasta que el cuerpo forme una línea recta. Aprieta glúteos arriba.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '15-20', advanced: '15-20' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'superman_back',
    name: 'Superman Hold',
    nameEs: 'Superman',
    muscleGroup: 'core', muscleTarget: 'lower_back',
    primaryMuscles: ['lower_back'], secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_CORE,
    instructions: [
      'Boca abajo con brazos extendidos al frente. Piernas rectas.',
      'Eleva brazos, pecho y piernas simultáneamente del suelo.',
      'Pausa 2-3 segundos en la posición alta. Baja con control.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '10-12', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'bird_dog',
    name: 'Bird Dog',
    nameEs: 'Perro Pájaro',
    muscleGroup: 'core', muscleTarget: 'lower_back',
    primaryMuscles: ['lower_back'], secondaryMuscles: ['abs', 'glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.2,
    image: IMG_CORE,
    instructions: [
      'A cuatro patas con espalda recta. Manos bajo hombros, rodillas bajo caderas.',
      'Extiende el brazo derecho y la pierna izquierda simultáneamente. Pausa 2 seg.',
      'Regresa y alterna. Activa músculos estabilizadores profundos de la columna.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '8 c/u', intermediate: '10 c/u', advanced: '12 c/u' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'cable_pull_through',
    name: 'Cable Pull Through',
    nameEs: 'Tirón en Polea entre Piernas',
    muscleGroup: 'core', muscleTarget: 'lower_back',
    primaryMuscles: ['lower_back'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['cable'], difficulty: 1, type: 'compound', compoundBonus: 1.4,
    image: IMG_GYM,
    instructions: [
      'De espaldas a la polea baja. Agarra la cuerda entre las piernas.',
      'Inclina el torso hacia adelante empujando las caderas atrás.',
      'Regresa a posición erguida apretando glúteos y lumbar. Similar al peso muerto.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
]
