import type { Exercise } from '../../types'

const IMG_LEGS = 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop'
const IMG_GYM  = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const LEG_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // CUÁDRICEPS (quad)
  // ══════════════════════════════════════════

  {
    id: 'squat_barbell',
    name: 'Barbell Back Squat',
    nameEs: 'Sentadilla con Barra',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_LEGS,
    instructions: [
      'Barra en la nuca, pies al ancho de hombros o ligeramente más abiertos.',
      'Baja empujando rodillas afuera y cadera hacia atrás hasta muslos paralelos al suelo.',
      'Empuja el suelo con los pies para subir. Mantén el pecho arriba en todo momento.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '8-10', intermediate: '6-10', advanced: '4-8' },
    rest: { beginner: 150, intermediate: 120, advanced: 90 },
  },
  {
    id: 'squat_goblet',
    name: 'Goblet Squat',
    nameEs: 'Sentadilla Goblet',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'core'],
    equipment: ['dumbbell', 'kettlebell'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_LEGS,
    instructions: [
      'Sostén la mancuerna o kettlebell vertical frente al pecho con ambas manos.',
      'Pies al ancho de hombros o algo más. Baja hasta profundidad máxima.',
      'El peso al frente favorece el torso erguido. Empuja hacia arriba.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-15', intermediate: '10-15', advanced: '12-15' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    nameEs: 'Prensa de Piernas',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_GYM,
    instructions: [
      'Pies al ancho de hombros en la plataforma. Ajusta el asiento para rodillas a 90°.',
      'Empuja la plataforma hasta casi extender las rodillas (no bloquees).',
      'Baja con control hasta que los muslos queden paralelos o más abajo.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-12' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    nameEs: 'Extensión de Pierna en Máquina',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta el rodillo para que quede en los tobillos. Espalda recta contra el respaldo.',
      'Extiende las piernas hasta arriba apretando el cuádriceps al final.',
      'Baja con control en 2-3 segundos. No dejes caer el peso.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat Machine',
    nameEs: 'Hack Squat en Máquina',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['machine'], difficulty: 2, type: 'compound', compoundBonus: 1.8,
    image: IMG_GYM,
    instructions: [
      'Espalda y hombros contra los pads. Pies ligeramente adelantados.',
      'Baja hasta que los muslos queden paralelos al suelo o más abajo.',
      'Empuja hacia arriba explosivamente. Gran sobrecarga del cuádriceps.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    nameEs: 'Sentadilla Búlgara',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_LEGS,
    instructions: [
      'Pie trasero en el banco. Pie delantero adelantado lo suficiente para alineación de rodilla.',
      'Baja la rodilla trasera hacia el suelo manteniendo el torso erguido.',
      'Empuja desde el talón del pie delantero para subir. Glúteo y cuádriceps.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '8-10 c/u', intermediate: '8-12 c/u', advanced: '8-12 c/u' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'lunge_dumbbell',
    name: 'Dumbbell Walking Lunge',
    nameEs: 'Zancadas con Mancuernas',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell'], difficulty: 1, type: 'compound', compoundBonus: 1.7,
    image: IMG_LEGS,
    instructions: [
      'De pie con mancuernas a los lados. Da un paso largo hacia adelante.',
      'Baja la rodilla trasera casi al suelo manteniendo el torso erguido.',
      'Empuja hacia adelante con el pie delantero y alterna la pierna.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10 c/u', intermediate: '12 c/u', advanced: '12-15 c/u' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    nameEs: 'Sentadilla con Peso Corporal',
    muscleGroup: 'lowerBody', muscleTarget: 'quad',
    primaryMuscles: ['quads'], secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.3,
    image: IMG_LEGS,
    instructions: [
      'Pies al ancho de hombros. Brazos al frente para equilibrio.',
      'Baja empujando caderas hacia atrás y rodillas hacia afuera hasta paralelo.',
      'Empuja hacia arriba apretando glúteos en la posición alta.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '20-30', advanced: '30-50' },
    rest: { beginner: 75, intermediate: 60, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // ISQUIOTIBIALES (hamstring)
  // ══════════════════════════════════════════

  {
    id: 'romanian_deadlift_barbell',
    name: 'Romanian Deadlift',
    nameEs: 'Peso Muerto Rumano con Barra',
    muscleGroup: 'lowerBody', muscleTarget: 'hamstring',
    primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_LEGS,
    instructions: [
      'De pie con barra frente a los muslos. Rodillas ligeramente flexionadas.',
      'Inclina el torso hacia adelante empujando las caderas atrás. Espalda recta.',
      'Siente el estiramiento en los isquiotibiales. Regresa apretando glúteos.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '6-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'romanian_deadlift_dumbbell',
    name: 'Dumbbell Romanian Deadlift',
    nameEs: 'Peso Muerto Rumano con Mancuernas',
    muscleGroup: 'lowerBody', muscleTarget: 'hamstring',
    primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'back'],
    equipment: ['dumbbell'], difficulty: 1, type: 'compound', compoundBonus: 1.7,
    image: IMG_LEGS,
    instructions: [
      'De pie con mancuernas frente a los muslos. Mayor rango de movimiento que con barra.',
      'Inclina el torso hacia adelante deslizando las mancuernas por las piernas.',
      'Regresa a posición erguida apretando isquiotibiales y glúteos.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '10-12', advanced: '8-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'leg_curl_lying',
    name: 'Lying Leg Curl',
    nameEs: 'Curl de Pierna Acostado',
    muscleGroup: 'lowerBody', muscleTarget: 'hamstring',
    primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Boca abajo en la máquina. Rodillo en la parte baja de los tobillos.',
      'Curva las piernas llevando los talones hacia los glúteos. Aprieta arriba.',
      'Baja con control en 2-3 segundos. No dejes caer el peso.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'leg_curl_seated',
    name: 'Seated Leg Curl',
    nameEs: 'Curl de Pierna Sentado',
    muscleGroup: 'lowerBody', muscleTarget: 'hamstring',
    primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta el respaldo y el rodillo superior sobre los muslos.',
      'Lleva los pies hacia atrás bajo el asiento apretando los isquiotibiales.',
      'Regresa con control. La posición sentada ofrece mayor rango en el bíceps femoral.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    nameEs: 'Curl Nórdico',
    muscleGroup: 'lowerBody', muscleTarget: 'hamstring',
    primaryMuscles: ['hamstrings'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 3, type: 'isolation', compoundBonus: 1.5,
    image: IMG_LEGS,
    instructions: [
      'Arrodíllate y asegura los tobillos bajo algo fijo. Cuerpo erguido.',
      'Baja el torso hacia el suelo lo más lento posible resistiendo con los isquiotibiales.',
      'Usa las manos para apoyarte abajo y regresa contrayendo los isquiotibiales.',
    ],
    sets: { beginner: '2-3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '3-5', intermediate: '5-8', advanced: '8-10' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },

  // ══════════════════════════════════════════
  // GLÚTEOS (glute)
  // ══════════════════════════════════════════

  {
    id: 'hip_thrust_barbell',
    name: 'Barbell Hip Thrust',
    nameEs: 'Hip Thrust con Barra',
    muscleGroup: 'lowerBody', muscleTarget: 'glute',
    primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'], difficulty: 2, type: 'compound', compoundBonus: 1.9,
    image: IMG_LEGS,
    instructions: [
      'Espalda alta apoyada en el banco. Barra sobre las caderas con almohadilla.',
      'Empuja las caderas hacia arriba apretando fuerte los glúteos arriba.',
      'Mantén 1-2 segundos en la cima. Baja con control hasta casi tocar el suelo.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'hip_thrust_dumbbell',
    name: 'Dumbbell Hip Thrust',
    nameEs: 'Hip Thrust con Mancuerna',
    muscleGroup: 'lowerBody', muscleTarget: 'glute',
    primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbell', 'bench'], difficulty: 1, type: 'compound', compoundBonus: 1.7,
    image: IMG_LEGS,
    instructions: [
      'Espalda alta apoyada en el banco. Mancuerna sobre las caderas.',
      'Empuja las caderas arriba apretando los glúteos al máximo.',
      'Pausa 2 segundos arriba. Baja con control hasta casi el suelo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    nameEs: 'Puente de Glúteos',
    muscleGroup: 'lowerBody', muscleTarget: 'glute',
    primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.3,
    image: IMG_LEGS,
    instructions: [
      'Acuéstate boca arriba con rodillas flexionadas y pies apoyados.',
      'Eleva las caderas apretando los glúteos hasta que el cuerpo forme una línea.',
      'Pausa 2 segundos arriba apretando glúteos. Baja con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '20-25' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'cable_kickback',
    name: 'Cable Glute Kickback',
    nameEs: 'Patada de Glúteo en Polea',
    muscleGroup: 'lowerBody', muscleTarget: 'glute',
    primaryMuscles: ['glutes'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Coloca el accesorio en el tobillo. Inclínate ligeramente hacia adelante.',
      'Lleva la pierna hacia atrás y arriba apretando el glúteo al máximo.',
      'Regresa con control. No permitas que la cadera rote.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15 c/u', intermediate: '12-15 c/u', advanced: '15-20 c/u' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'sumo_squat_dumbbell',
    name: 'Sumo Squat',
    nameEs: 'Sentadilla Sumo con Mancuerna',
    muscleGroup: 'lowerBody', muscleTarget: 'glute',
    primaryMuscles: ['glutes'], secondaryMuscles: ['quads', 'adductors'],
    equipment: ['dumbbell'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_LEGS,
    instructions: [
      'Pies más anchos que los hombros, puntas hacia afuera a 45°. Mancuerna entre piernas.',
      'Baja manteniendo el torso erguido y rodillas en línea con los dedos.',
      'Empuja hacia arriba apretando glúteos e internos de muslo en la cima.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '10-12', advanced: '10-12' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // PANTORRILLAS (calf)
  // ══════════════════════════════════════════

  {
    id: 'calf_raise_standing_machine',
    name: 'Standing Calf Raise Machine',
    nameEs: 'Elevación de Pantorrillas en Máquina',
    muscleGroup: 'lowerBody', muscleTarget: 'calf',
    primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Coloca los hombros bajo los pads. Pies en el borde de la plataforma.',
      'Eleva los talones lo más alto posible apretando las pantorrillas.',
      'Baja lentamente por debajo del nivel de la plataforma para estirar.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '15-20', intermediate: '12-15', advanced: '10-12' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
  {
    id: 'calf_raise_seated',
    name: 'Seated Calf Raise',
    nameEs: 'Elevación de Pantorrillas Sentado',
    muscleGroup: 'lowerBody', muscleTarget: 'calf',
    primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Rodillas bajo el pad. Pies en el borde de la plataforma.',
      'Eleva los talones lo más posible. La posición sentada activa más el sóleo.',
      'Baja hasta estiramiento máximo. Pausa 1 segundo abajo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'calf_raise_bodyweight',
    name: 'Bodyweight Calf Raise',
    nameEs: 'Elevación de Pantorrillas con Peso Corporal',
    muscleGroup: 'lowerBody', muscleTarget: 'calf',
    primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['bodyweight'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_LEGS,
    instructions: [
      'De pie en un escalón o borde. Solo la parte delantera del pie apoyada.',
      'Eleva los talones lo más alto posible. Pausa 2 segundos arriba.',
      'Baja controlado por debajo del nivel del escalón para máximo estiramiento.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '20-30', advanced: '30-50' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'calf_raise_leg_press',
    name: 'Leg Press Calf Raise',
    nameEs: 'Elevación de Pantorrilla en Prensa',
    muscleGroup: 'lowerBody', muscleTarget: 'calf',
    primaryMuscles: ['calves'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'En la prensa, coloca solo la punta de los pies en el borde de la plataforma.',
      'Extiende los tobillos empujando la plataforma con los dedos del pie.',
      'Regresa con control hasta estiramiento completo.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },

  // ══════════════════════════════════════════
  // ADUCTORES (adductor)
  // ══════════════════════════════════════════

  {
    id: 'machine_adduction',
    name: 'Inner Thigh Machine',
    nameEs: 'Aducción en Máquina',
    muscleGroup: 'lowerBody', muscleTarget: 'adductor',
    primaryMuscles: ['adductors'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Siéntate con piernas separadas sobre los pads exteriores.',
      'Cierra las piernas resistiendo el peso. Aprieta los aductores.',
      'Regresa lentamente con control. Mantén la espalda recta.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'cable_adduction',
    name: 'Cable Hip Adduction',
    nameEs: 'Aducción de Cadera en Polea',
    muscleGroup: 'lowerBody', muscleTarget: 'adductor',
    primaryMuscles: ['adductors'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'Accesorio en tobillo lateral. De pie con la polea al costado.',
      'Cruza la pierna hacia adelante del cuerpo activando los aductores.',
      'Regresa con control manteniendo el balance sobre una pierna.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15 c/u', intermediate: '12-15 c/u', advanced: '15-20 c/u' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'lateral_lunge',
    name: 'Lateral Lunge',
    nameEs: 'Zancada Lateral',
    muscleGroup: 'lowerBody', muscleTarget: 'adductor',
    primaryMuscles: ['adductors'], secondaryMuscles: ['glutes', 'quads'],
    equipment: ['bodyweight'], difficulty: 1, type: 'compound', compoundBonus: 1.4,
    image: IMG_LEGS,
    instructions: [
      'De pie. Da un paso amplio hacia el costado. Pierna de apoyo recta.',
      'Dobla la rodilla de la pierna que da el paso empujando la cadera atrás.',
      'Regresa empujando desde el talón. Activa aductores e isquio al subir.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10 c/u', intermediate: '12 c/u', advanced: '12-15 c/u' },
    rest: { beginner: 75, intermediate: 60, advanced: 60 },
  },
]
