import type { Exercise } from '../../types'

const IMG_SHOULDER = 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop'
const IMG_GYM      = 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop'

export const SHOULDER_EXERCISES: Exercise[] = [

  // ══════════════════════════════════════════
  // DELTOIDES ANTERIOR (shoulder_front)
  // ══════════════════════════════════════════

  {
    id: 'overhead_press_barbell',
    name: 'Barbell Overhead Press',
    nameEs: 'Press Militar con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 2.0,
    image: IMG_SHOULDER,
    instructions: [
      'De pie o sentado. Barra a la altura de la clavícula, agarre algo más ancho que hombros.',
      'Empuja hacia arriba mientras metes la cabeza hacia atrás para dejar pasar la barra.',
      'Extiende completamente los brazos arriba y baja con control a la clavícula.',
    ],
    sets: { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps: { beginner: '8-10', intermediate: '6-10', advanced: '5-8' },
    rest: { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'overhead_press_dumbbell',
    name: 'Dumbbell Shoulder Press',
    nameEs: 'Press de Hombro con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'], difficulty: 1, type: 'compound', compoundBonus: 1.8,
    image: IMG_SHOULDER,
    instructions: [
      'Sentado o de pie. Mancuernas a la altura de los hombros con codos a 90°.',
      'Empuja hacia arriba y ligeramente adentro hasta casi tocar las mancuernas.',
      'Baja con control hasta la posición inicial. Mayor rango que con barra.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    nameEs: 'Press Arnold',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'], difficulty: 2, type: 'compound', compoundBonus: 1.7,
    image: IMG_SHOULDER,
    instructions: [
      'Sentado con mancuernas frente al pecho, palmas hacia ti (supino).',
      'Gira las palmas hacia afuera mientras empujas hacia arriba en un movimiento rotacional.',
      'Al extender los brazos, palmas apuntan adelante. Invierte al bajar.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'front_raise_dumbbell',
    name: 'Dumbbell Front Raise',
    nameEs: 'Elevación Frontal con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_SHOULDER,
    instructions: [
      'De pie con mancuernas frente a los muslos, palmas hacia adentro.',
      'Eleva los brazos al frente hasta la altura de los hombros. Ligeramente flexionados.',
      'Baja lentamente con control. Alterna brazos o muévelos simultáneamente.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'front_raise_cable',
    name: 'Cable Front Raise',
    nameEs: 'Elevación Frontal en Polea',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'De pie de espaldas a la polea baja. Agarra el mango con una mano.',
      'Eleva el brazo al frente hasta la altura del hombro manteniendo tensión constante.',
      'Baja con control. La polea mantiene tensión durante todo el recorrido.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    nameEs: 'Press de Hombros en Máquina',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_front',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'],
    equipment: ['machine'], difficulty: 1, type: 'compound', compoundBonus: 1.6,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento para que las asas queden a la altura de los hombros.',
      'Empuja hacia arriba hasta casi extender los codos. No bloquees completamente.',
      'Baja con control hasta la posición inicial manteniendo tensión en los hombros.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // DELTOIDES LATERAL (shoulder_side)
  // ══════════════════════════════════════════

  {
    id: 'lateral_raise_dumbbell',
    name: 'Dumbbell Lateral Raise',
    nameEs: 'Elevación Lateral con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_side',
    primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_SHOULDER,
    instructions: [
      'De pie con mancuernas a los lados. Ligera flexión de codo (15-20°).',
      'Eleva los brazos hacia los lados hasta la altura de los hombros. Pulgares ligeramente hacia abajo.',
      'Baja con control en 2-3 segundos. No uses impulso.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'lateral_raise_cable',
    name: 'Cable Lateral Raise',
    nameEs: 'Elevación Lateral en Polea',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_side',
    primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_GYM,
    instructions: [
      'De pie al lado de la polea baja. Agarra el mango con la mano alejada.',
      'Eleva el brazo al costado hasta la altura del hombro.',
      'Baja lentamente. La polea mantiene tensión incluso en la posición baja.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'machine_lateral_raise',
    name: 'Machine Lateral Raise',
    nameEs: 'Elevación Lateral en Máquina',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_side',
    primaryMuscles: ['shoulders'], secondaryMuscles: [],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Ajusta el asiento para que los brazos queden alineados con el pivote.',
      'Empuja los brazos hacia arriba y afuera hasta la altura de los hombros.',
      'Baja con control sin dejar caer el peso. Mayor aislamiento que con mancuernas.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'upright_row_barbell',
    name: 'Barbell Upright Row',
    nameEs: 'Remo al Cuello con Barra',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_side',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back', 'biceps'],
    equipment: ['barbell'], difficulty: 2, type: 'compound', compoundBonus: 1.6,
    image: IMG_SHOULDER,
    instructions: [
      'Agarra la barra con agarre prono al ancho de hombros o más estrecho.',
      'Jala la barra hacia arriba a lo largo del cuerpo hasta la altura del pecho.',
      'Los codos deben ir por encima de la barra. Baja con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest: { beginner: 90, intermediate: 75, advanced: 60 },
  },

  // ══════════════════════════════════════════
  // DELTOIDES POSTERIOR (shoulder_rear)
  // ══════════════════════════════════════════

  {
    id: 'rear_delt_fly_dumbbell',
    name: 'Rear Delt Fly',
    nameEs: 'Apertura de Deltoides Posterior con Mancuernas',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_rear',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back'],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_SHOULDER,
    instructions: [
      'De pie o sentado, inclina el torso a 45-90°. Mancuernas colgando.',
      'Eleva los brazos hacia los lados y arriba hasta la altura de los hombros.',
      'Aprieta los deltoides posteriores al máximo. Baja lentamente.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'rear_delt_fly_machine',
    name: 'Pec Deck Rear Delt',
    nameEs: 'Apertura Posterior en Contractora',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_rear',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back'],
    equipment: ['machine'], difficulty: 1, type: 'isolation', compoundBonus: 1.0,
    image: IMG_GYM,
    instructions: [
      'Siéntate de frente al respaldo de la contractora. Agarra las asas externas.',
      'Abre los brazos hacia atrás apretando el deltoides posterior.',
      'Regresa con control. Mayor aislamiento que con mancuernas.',
    ],
    sets: { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'face_pull_shoulder',
    name: 'Face Pull (Rear Delt Focus)',
    nameEs: 'Face Pull (Foco Posterior)',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_rear',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back'],
    equipment: ['cable'], difficulty: 1, type: 'isolation', compoundBonus: 1.2,
    image: IMG_GYM,
    instructions: [
      'Polea a la altura de los ojos. Cuerda con agarre neutro.',
      'Jala hacia la cara separando manos y llevando codos afuera a 90°.',
      'Mantén el pecho afuera y aprieta los deltoides posteriores.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '15-20', intermediate: '15-20', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'bent_over_lateral_raise',
    name: 'Bent Over Lateral Raise',
    nameEs: 'Elevación Lateral Inclinada',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_rear',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back'],
    equipment: ['dumbbell'], difficulty: 1, type: 'isolation', compoundBonus: 1.1,
    image: IMG_SHOULDER,
    instructions: [
      'Sentado al borde del banco, inclina el torso al frente hasta paralelo al suelo.',
      'Eleva las mancuernas hacia los lados con codos ligeramente flexionados.',
      'Aprieta arriba y baja lentamente. No uses el torso para ayudarte.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'reverse_fly_cable',
    name: 'Reverse Cable Fly',
    nameEs: 'Apertura Inversa en Poleas',
    muscleGroup: 'upperBody', muscleTarget: 'shoulder_rear',
    primaryMuscles: ['shoulders'], secondaryMuscles: ['back'],
    equipment: ['cable'], difficulty: 2, type: 'isolation', compoundBonus: 1.2,
    image: IMG_GYM,
    instructions: [
      'Cruza los cables (polea derecha para mano izquierda y viceversa).',
      'De pie en el centro. Abre los brazos hacia afuera en arco.',
      'Aprieta los deltoides posteriores y romboides al final. Regresa con control.',
    ],
    sets: { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps: { beginner: '12-15', intermediate: '12-15', advanced: '12-15' },
    rest: { beginner: 60, intermediate: 60, advanced: 45 },
  },
]
