-- ============================================================
-- LIFEFYT — Exercise Bank Seed
-- Auto-generated by scripts/generate-exercises-sql.ts
-- Run AFTER exercises_schema.sql
-- ============================================================

INSERT INTO exercises (
  id, name, name_es,
  muscle_group, muscle_target,
  primary_muscles, secondary_muscles, equipment,
  difficulty, type, compound_bonus, image,
  instructions,
  sets_beginner, sets_intermediate, sets_advanced,
  reps_beginner, reps_intermediate, reps_advanced,
  rest_beginner, rest_intermediate, rest_advanced
) VALUES
  (
    'incline_press_barbell', 'Incline Barbell Bench Press', 'Press Inclinado con Barra',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders","triceps"}', '{"barbell","bench"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Ajusta el banco entre 30-45°. Agarra la barra a una anchura mayor que los hombros.","Baja la barra hasta la clavícula de forma controlada (2-3 seg).","Empuja hacia arriba y ligeramente hacia atrás hasta extender los codos."}',
    '3', '4', '4-5',
    '10-12', '8-12', '6-10',
    120, 90, 75
  ),
  (
    'incline_press_dumbbell', 'Incline Dumbbell Press', 'Press Inclinado con Mancuernas',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders","triceps"}', '{"dumbbell","bench"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Banco a 30-45°. Sostén las mancuernas a la altura del pecho con codos a 75°.","Empuja hacia arriba y adentro hasta que las mancuernas casi se toquen.","Baja con control en 2-3 segundos manteniendo tensión en el pecho."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'incline_press_smith', 'Incline Smith Machine Press', 'Press Inclinado en Máquina Smith',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders","triceps"}', '{"machine","bench"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Coloca el banco inclinado bajo la barra Smith. Ajusta el agarre a anchura de hombros.","Desbloquea la barra y bájala hasta la parte superior del pecho.","Empuja hacia arriba de forma explosiva hasta casi extender los codos."}',
    '3', '3-4', '4',
    '12-15', '10-12', '8-12',
    90, 75, 60
  ),
  (
    'incline_fly_dumbbell', 'Incline Dumbbell Fly', 'Aperturas Inclinadas con Mancuernas',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders"}', '{"dumbbell","bench"}',
    2, 'isolation', 1.2, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Banco a 30°. Sostén mancuernas con brazos semi-extendidos encima del pecho.","Abre los brazos en arco amplio bajando hasta sentir estiramiento en el pecho.","Cierra los brazos como si abrazaras un árbol grande. No bloquees los codos."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'cable_fly_low_to_high', 'Cable Crossover Low to High', 'Cruce de Poleas Bajo hacia Alto',
    'upperBody', 'chest_upper',
    '{"chest"}', '{}', '{"cable"}',
    2, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Poleas en posición baja. De pie en el centro, un pie adelante.","Lleva los cables hacia arriba y al frente, cruzando las manos a la altura del pecho.","Regresa lentamente al punto inicial manteniendo tensión constante."}',
    '3', '3-4', '4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'pec_deck_upper', 'Pec Deck (Upper Focus)', 'Contractora de Pecho Superior',
    'upperBody', 'chest_upper',
    '{"chest"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento para que los codos queden a la altura de los hombros o ligeramente por debajo.","Cierra los brazos hasta el centro apretando el pecho al final del recorrido.","Regresa con control sin soltar la tensión muscular."}',
    '3', '3', '3-4',
    '12-15', '12-15', '10-12',
    60, 60, 45
  ),
  (
    'push_up_feet_elevated', 'Feet Elevated Push Up', 'Flexión con Pies Elevados',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders","triceps"}', '{"bodyweight","bench"}',
    2, 'compound', 1.5, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Coloca los pies sobre un banco o superficie elevada. Manos al ancho de hombros en el suelo.","Baja el pecho hacia el suelo manteniendo el cuerpo recto.","Empuja hacia arriba de forma explosiva. El ángulo activa el pecho superior."}',
    '3', '3-4', '4',
    '8-10', '10-15', '15-20',
    90, 75, 60
  ),
  (
    'hammer_strength_incline', 'Hammer Strength Incline Press', 'Press Inclinado Hammer Strength',
    'upperBody', 'chest_upper',
    '{"chest"}', '{"shoulders","triceps"}', '{"machine"}',
    2, 'compound', 1.7, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento para que las asas queden a la altura del pecho superior.","Empuja las asas hacia arriba y al frente hasta casi extender los codos.","Regresa con control manteniendo los omóplatos juntos contra el respaldo."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'bench_press_barbell', 'Barbell Bench Press', 'Press de Banca con Barra',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"triceps","shoulders"}', '{"barbell","bench"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Acuéstate en el banco con los pies apoyados en el suelo. Arco natural en la espalda baja.","Agarra la barra a una anchura mayor que los hombros. Retrae los omóplatos.","Baja la barra hasta el pecho medio de forma controlada y empuja explosivamente hacia arriba."}',
    '3', '4', '5',
    '8-10', '8-12', '6-10',
    120, 90, 75
  ),
  (
    'bench_press_dumbbell', 'Dumbbell Bench Press', 'Press de Banca con Mancuernas',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"triceps","shoulders"}', '{"dumbbell","bench"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Acuéstate con mancuernas a la altura del pecho, codos a 75° del cuerpo.","Empuja hacia arriba y adentro hasta que las mancuernas casi se toquen arriba.","Baja con control en 2-3 segundos hasta sentir estiramiento en el pecho."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'bench_press_smith', 'Smith Machine Bench Press', 'Press de Banca en Máquina Smith',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"triceps","shoulders"}', '{"machine","bench"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Coloca el banco plano bajo la barra Smith. Agarre al ancho de hombros.","Baja la barra al pecho de forma controlada. La máquina guía el movimiento.","Empuja hasta casi extender los codos. No bloquees completamente."}',
    '3', '3-4', '4',
    '12-15', '10-12', '8-12',
    90, 75, 60
  ),
  (
    'dumbbell_fly_flat', 'Flat Dumbbell Fly', 'Aperturas con Mancuernas en Banco Plano',
    'upperBody', 'chest_mid',
    '{"chest"}', '{}', '{"dumbbell","bench"}',
    2, 'isolation', 1.2, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Acuéstate en banco plano con mancuernas extendidas sobre el pecho.","Abre los brazos en arco amplio bajando hasta sentir estiramiento completo.","Cierra los brazos como si abrazaras un barril. Aprieta el pecho arriba."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'cable_fly_mid', 'Cable Fly Mid', 'Cruce de Poleas Medio',
    'upperBody', 'chest_mid',
    '{"chest"}', '{}', '{"cable"}',
    2, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Poleas a la altura de los hombros. De pie en el centro con un pie adelante.","Lleva los cables al frente cruzando las manos a la altura del ombligo.","Regresa lentamente controlando la apertura sin perder tensión en el pecho."}',
    '3', '3-4', '4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'pec_deck_flat', 'Pec Deck Machine', 'Contractora de Pecho',
    'upperBody', 'chest_mid',
    '{"chest"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate con la espalda recta contra el respaldo. Ajusta el asiento.","Cierra los brazos hasta el centro apretando el pecho en el punto máximo.","Regresa con control sin dejar caer el peso. Mantén tensión constante."}',
    '3', '3', '3-4',
    '12-15', '12-15', '10-12',
    60, 60, 45
  ),
  (
    'push_up_standard', 'Standard Push Up', 'Flexión de Brazos Estándar',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"triceps","shoulders"}', '{"bodyweight"}',
    1, 'compound', 1.5, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Posición de plancha alta, manos al ancho de hombros. Cuerpo recto de cabeza a talones.","Baja el pecho al suelo manteniendo los codos a 45° del cuerpo.","Empuja hacia arriba de forma explosiva. Aprieta el pecho arriba."}',
    '3', '3-4', '4',
    '8-12', '12-20', '20-30',
    90, 75, 60
  ),
  (
    'push_up_wide', 'Wide Grip Push Up', 'Flexión con Agarre Ancho',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"shoulders"}', '{"bodyweight"}',
    1, 'compound', 1.4, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Manos significativamente más anchas que los hombros. Dedos apuntando hacia afuera.","Baja el pecho entre las manos sintiendo el estiramiento en el pecho.","Empuja hacia arriba apretando el pecho en la posición alta."}',
    '3', '3-4', '4',
    '8-12', '12-20', '20-30',
    90, 75, 60
  ),
  (
    'hammer_strength_flat', 'Hammer Strength Flat Press', 'Press Plano Hammer Strength',
    'upperBody', 'chest_mid',
    '{"chest"}', '{"triceps","shoulders"}', '{"machine"}',
    2, 'compound', 1.7, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate con la espalda apoyada. Agarra las asas a la altura del pecho medio.","Empuja hacia adelante hasta casi extender los codos. Aprieta el pecho.","Regresa con control hasta sentir estiramiento completo en el pecho."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'decline_press_barbell', 'Decline Barbell Press', 'Press Declinado con Barra',
    'upperBody', 'chest_lower',
    '{"chest"}', '{"triceps"}', '{"barbell","bench"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Banco declinado a -15 a -30°. Asegura los pies. Agarre al ancho de hombros.","Baja la barra hasta el pecho inferior de forma controlada.","Empuja hacia arriba y ligeramente hacia la cabeza hasta extender los codos."}',
    '3', '4', '4-5',
    '10-12', '8-12', '6-10',
    120, 90, 75
  ),
  (
    'decline_press_dumbbell', 'Decline Dumbbell Press', 'Press Declinado con Mancuernas',
    'upperBody', 'chest_lower',
    '{"chest"}', '{"triceps"}', '{"dumbbell","bench"}',
    2, 'compound', 1.7, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Banco declinado. Sostén las mancuernas a la altura del pecho inferior.","Empuja hacia arriba y ligeramente adentro hasta casi tocar las mancuernas.","Baja con control en 2-3 segundos hasta el estiramiento máximo."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'chest_dip', 'Chest Dip', 'Fondos en Barras (Pecho)',
    'upperBody', 'chest_lower',
    '{"chest"}', '{"triceps","shoulders"}', '{"bodyweight"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Agarra las barras paralelas. Inclina el torso hacia adelante (30-45°).","Baja el cuerpo hasta que los codos formen 90°, sintiendo estiramiento en el pecho.","Empuja hacia arriba usando el pecho inferior. Mantén la inclinación hacia adelante."}',
    '3', '3-4', '4',
    '6-8', '8-12', '12-15',
    120, 90, 75
  ),
  (
    'cable_fly_high_to_low', 'Cable Crossover High to Low', 'Cruce de Poleas Alto hacia Bajo',
    'upperBody', 'chest_lower',
    '{"chest"}', '{}', '{"cable"}',
    2, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Poleas en posición alta. De pie en el centro, un pie adelante para estabilidad.","Lleva los cables hacia abajo y al frente, cruzando las manos a la altura de las caderas.","Regresa lentamente al punto inicial controlando la apertura."}',
    '3', '3-4', '4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'push_up_decline', 'Decline Push Up', 'Flexión Declinada',
    'upperBody', 'chest_lower',
    '{"chest"}', '{"triceps"}', '{"bodyweight"}',
    1, 'compound', 1.4, 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    '{"Manos en el suelo al ancho de hombros. Pies elevados en una silla o banco.","Baja el pecho hacia el suelo manteniendo el cuerpo recto.","Empuja hacia arriba de forma explosiva. Activa el pecho inferior."}',
    '3', '3-4', '4',
    '8-12', '12-20', '20-30',
    90, 75, 60
  ),
  (
    'dip_assisted', 'Assisted Dip Machine', 'Fondos Asistidos en Máquina',
    'upperBody', 'chest_lower',
    '{"chest"}', '{"triceps"}', '{"machine"}',
    1, 'compound', 1.5, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Selecciona el peso de asistencia. A mayor asistencia, menor dificultad.","Inclina el torso hacia adelante para activar más el pecho.","Baja hasta 90° de flexión de codo, luego empuja hacia arriba."}',
    '3', '3', '3-4',
    '10-12', '10-12', '12-15',
    90, 75, 60
  ),
  (
    'pull_up', 'Pull Up', 'Dominadas',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"pullup_bar","bodyweight"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Agarra la barra con las palmas hacia afuera, más ancho que los hombros.","Tira hacia arriba llevando el pecho a la barra. Activa los dorsales.","Baja de forma controlada hasta extender completamente los brazos."}',
    '3', '4', '4-5',
    '3-6', '6-10', '8-12',
    120, 90, 75
  ),
  (
    'chin_up', 'Chin Up', 'Dominadas Supinas',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"pullup_bar","bodyweight"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Agarra la barra con palmas hacia ti (supino) al ancho de hombros.","Tira hacia arriba llevando el mentón sobre la barra. Codos hacia abajo.","Baja con control hasta extensión completa. Mayor activación de bíceps."}',
    '3', '4', '4-5',
    '4-6', '6-10', '8-12',
    120, 90, 75
  ),
  (
    'lat_pulldown_wide', 'Wide Grip Lat Pulldown', 'Jalón al Pecho Agarre Ancho',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"machine","cable"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate con las rodillas bajo el rodillo. Agarra la barra más ancha que los hombros.","Jala la barra hacia el pecho superior apretando los dorsales al final.","Regresa lentamente hasta extensión completa. No balancees el torso."}',
    '3', '4', '4-5',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'lat_pulldown_neutral', 'Neutral Grip Lat Pulldown', 'Jalón Agarre Neutro',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"machine","cable"}',
    1, 'compound', 1.7, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Usa una barra con agarre neutro (palmas enfrentadas) al ancho de hombros.","Jala hacia abajo llevando las manos a los lados del pecho.","Aprieta los dorsales en la posición baja y regresa con control."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'single_arm_dumbbell_row', 'Single Arm Dumbbell Row', 'Remo con Mancuerna a Una Mano',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"dumbbell","bench"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Apoya una mano y rodilla en el banco. Espalda paralela al suelo.","Jala la mancuerna hacia la cadera llevando el codo hacia atrás y arriba.","Aprieta el dorsal en la parte alta y baja con control."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'straight_arm_pulldown', 'Straight Arm Pulldown', 'Jalón de Dorsal con Brazos Rectos',
    'upperBody', 'back_lats',
    '{"back"}', '{}', '{"cable"}',
    2, 'isolation', 1.3, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"De pie frente a la polea alta. Agarra la barra con brazos casi extendidos.","Lleva la barra hacia abajo hasta las caderas manteniendo los brazos rectos.","Aprieta los dorsales y regresa lentamente. Excelente aislamiento."}',
    '3', '3', '3-4',
    '12-15', '12-15', '10-12',
    75, 60, 60
  ),
  (
    'dumbbell_pullover', 'Dumbbell Pullover', 'Pullover con Mancuerna',
    'upperBody', 'back_lats',
    '{"back"}', '{"chest"}', '{"dumbbell","bench"}',
    2, 'isolation', 1.4, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Acuéstate transversal en el banco. Solo la parte alta de la espalda apoyada.","Sostén la mancuerna con ambas manos sobre el pecho, brazos semi-extendidos.","Baja la mancuerna hacia atrás de la cabeza en arco. Regresa apretando dorsal."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'assisted_pull_up', 'Assisted Pull Up', 'Dominadas Asistidas',
    'upperBody', 'back_lats',
    '{"back"}', '{"biceps"}', '{"machine"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el peso de asistencia. Más peso = menos dificultad.","Tira hacia arriba llevando el pecho a la barra, codos abajo y atrás.","Baja lentamente hasta extensión completa. Reduce asistencia progresivamente."}',
    '3', '3-4', '4',
    '8-12', '8-12', '10-15',
    90, 75, 60
  ),
  (
    'barbell_row', 'Barbell Bent Over Row', 'Remo con Barra Inclinado',
    'upperBody', 'back_upper',
    '{"back"}', '{"biceps"}', '{"barbell"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Inclina el torso a 45° con la barra colgando. Espalda recta y neutral.","Jala la barra hacia el ombligo apretando la espalda al final del recorrido.","Baja con control hasta brazos extendidos. Mantén la espalda recta en todo momento."}',
    '3', '4', '4-5',
    '8-10', '6-10', '5-8',
    120, 90, 75
  ),
  (
    'seated_cable_row', 'Seated Cable Row', 'Remo en Polea Sentado',
    'upperBody', 'back_upper',
    '{"back"}', '{"biceps"}', '{"cable","machine"}',
    1, 'compound', 1.7, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate con pies en el soporte, espalda recta y ligera inclinación adelante.","Jala el mango hacia el abdomen llevando los codos atrás y apretando la espalda.","Regresa con control hasta brazos extendidos. No te balancees."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'face_pull', 'Face Pull', 'Face Pull con Polea',
    'upperBody', 'back_upper',
    '{"back"}', '{"shoulders"}', '{"cable"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea a la altura de los ojos. Usa la cuerda con agarre neutro.","Jala hacia la cara separando las manos y llevando los codos hacia afuera.","Aprieta los romboides y deltoides posteriores al final. Regresa con control."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'barbell_shrug', 'Barbell Shrug', 'Encogimientos con Barra',
    'upperBody', 'back_upper',
    '{"back"}', '{}', '{"barbell"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"De pie con la barra en agarre prono al frente. Brazos extendidos.","Eleva los hombros hacia las orejas lo más alto posible. Aprieta 1 segundo.","Baja lentamente. No hagas círculos con los hombros, solo movimiento vertical."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'dumbbell_shrug', 'Dumbbell Shrug', 'Encogimientos con Mancuernas',
    'upperBody', 'back_upper',
    '{"back"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"De pie con mancuernas a los lados. Mayor rango de movimiento que con barra.","Eleva los hombros lo más alto posible. Pausa 1-2 segundos arriba.","Baja de forma controlada. Permite mayor amplitud de movimiento."}',
    '3', '3', '3-4',
    '12-15', '12-15', '12-15',
    75, 60, 60
  ),
  (
    'chest_supported_row', 'Chest Supported Dumbbell Row', 'Remo con Mancuernas en Banco Inclinado',
    'upperBody', 'back_mid',
    '{"back"}', '{"biceps"}', '{"dumbbell","bench"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Recuéstate boca abajo en banco inclinado a 45°. Mancuernas colgando.","Jala las mancuernas hacia arriba llevando los codos al techo.","Aprieta los romboides y la espalda media. Baja con control."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    90, 75, 60
  ),
  (
    'machine_row_chest', 'Machine Chest Supported Row', 'Remo en Máquina con Soporte de Pecho',
    'upperBody', 'back_mid',
    '{"back"}', '{"biceps"}', '{"machine"}',
    1, 'compound', 1.5, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento y el pecho contra el soporte. Agarra las asas.","Jala hacia atrás llevando los codos al máximo recorrido.","Aprieta la espalda media y regresa con control."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    90, 75, 60
  ),
  (
    'cable_row_wide', 'Wide Grip Cable Row', 'Remo en Polea Agarre Ancho',
    'upperBody', 'back_mid',
    '{"back"}', '{"biceps"}', '{"cable","machine"}',
    2, 'compound', 1.6, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Usa barra larga en la polea baja. Agarre prono más ancho que los hombros.","Jala hacia el abdomen llevando los codos al lado del cuerpo.","Activa romboides y espalda media apretando en la posición final."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'deadlift_conventional', 'Conventional Deadlift', 'Peso Muerto Convencional',
    'upperBody', 'back_lower',
    '{"back"}', '{"glutes","hamstrings","quads"}', '{"barbell"}',
    3, 'compound', 2, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Barra sobre los empeines. Cadera hacia atrás, espalda recta, agarre al ancho de caderas.","Empuja el suelo alejándolo y estira las caderas hacia adelante al subir.","Baja controlado: caderas atrás primero, luego dobla las rodillas al llegar a las tibias."}',
    '3', '4', '4-5',
    '5-6', '4-6', '3-5',
    180, 150, 120
  ),
  (
    'hyperextension', 'Hyperextension', 'Hiperextensión de Espalda',
    'upperBody', 'back_lower',
    '{"back"}', '{"glutes","hamstrings"}', '{"bodyweight"}',
    1, 'isolation', 1.3, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Posiciona las caderas en el borde del banco de hiperextensiones. Pies asegurados.","Baja el torso hacia el suelo manteniendo la espalda recta (no arqueada).","Levanta el torso hasta que quede en línea con las piernas. Aprieta los glúteos arriba."}',
    '3', '3-4', '4',
    '10-15', '10-15', '12-20',
    75, 60, 60
  ),
  (
    'good_morning', 'Good Morning', 'Buenos Días con Barra',
    'upperBody', 'back_lower',
    '{"back"}', '{"hamstrings","glutes"}', '{"barbell"}',
    2, 'compound', 1.7, 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&q=80&fit=crop',
    '{"Barra en la nuca. De pie con rodillas ligeramente flexionadas.","Inclina el torso hacia adelante empujando las caderas hacia atrás.","Regresa a posición erguida apretando glúteos e isquiotibiales."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 75
  ),
  (
    'back_extension_machine', 'Back Extension Machine', 'Extensión de Espalda en Máquina',
    'upperBody', 'back_lower',
    '{"back"}', '{"glutes"}', '{"machine"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta la máquina al tamaño de tu torso. Siéntate con espalda recta.","Empuja contra el soporte extendiendo la espalda hacia atrás.","Regresa con control a la posición inicial sin dejar caer el peso."}',
    '3', '3', '3-4',
    '12-15', '12-15', '12-15',
    75, 60, 60
  ),
  (
    'superman', 'Superman', 'Superman',
    'upperBody', 'back_lower',
    '{"back"}', '{"glutes"}', '{"bodyweight"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Boca abajo en el suelo con brazos extendidos al frente.","Eleva simultáneamente brazos, pecho y piernas del suelo. Pausa 2 segundos.","Baja con control. Excelente para activación lumbar sin carga."}',
    '3', '3', '3-4',
    '10-12', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'overhead_press_barbell', 'Barbell Overhead Press', 'Press Militar con Barra',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{"triceps"}', '{"barbell"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"De pie o sentado. Barra a la altura de la clavícula, agarre algo más ancho que hombros.","Empuja hacia arriba mientras metes la cabeza hacia atrás para dejar pasar la barra.","Extiende completamente los brazos arriba y baja con control a la clavícula."}',
    '3', '4', '4-5',
    '8-10', '6-10', '5-8',
    120, 90, 75
  ),
  (
    'overhead_press_dumbbell', 'Dumbbell Shoulder Press', 'Press de Hombro con Mancuernas',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{"triceps"}', '{"dumbbell"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"Sentado o de pie. Mancuernas a la altura de los hombros con codos a 90°.","Empuja hacia arriba y ligeramente adentro hasta casi tocar las mancuernas.","Baja con control hasta la posición inicial. Mayor rango que con barra."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'arnold_press', 'Arnold Press', 'Press Arnold',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{"triceps"}', '{"dumbbell"}',
    2, 'compound', 1.7, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"Sentado con mancuernas frente al pecho, palmas hacia ti (supino).","Gira las palmas hacia afuera mientras empujas hacia arriba en un movimiento rotacional.","Al extender los brazos, palmas apuntan adelante. Invierte al bajar."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'front_raise_dumbbell', 'Dumbbell Front Raise', 'Elevación Frontal con Mancuernas',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"De pie con mancuernas frente a los muslos, palmas hacia adentro.","Eleva los brazos al frente hasta la altura de los hombros. Ligeramente flexionados.","Baja lentamente con control. Alterna brazos o muévelos simultáneamente."}',
    '3', '3', '3-4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'front_raise_cable', 'Cable Front Raise', 'Elevación Frontal en Polea',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"De pie de espaldas a la polea baja. Agarra el mango con una mano.","Eleva el brazo al frente hasta la altura del hombro manteniendo tensión constante.","Baja con control. La polea mantiene tensión durante todo el recorrido."}',
    '3', '3', '3-4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'machine_shoulder_press', 'Machine Shoulder Press', 'Press de Hombros en Máquina',
    'upperBody', 'shoulder_front',
    '{"shoulders"}', '{"triceps"}', '{"machine"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento para que las asas queden a la altura de los hombros.","Empuja hacia arriba hasta casi extender los codos. No bloquees completamente.","Baja con control hasta la posición inicial manteniendo tensión en los hombros."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'lateral_raise_dumbbell', 'Dumbbell Lateral Raise', 'Elevación Lateral con Mancuernas',
    'upperBody', 'shoulder_side',
    '{"shoulders"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"De pie con mancuernas a los lados. Ligera flexión de codo (15-20°).","Eleva los brazos hacia los lados hasta la altura de los hombros. Pulgares ligeramente hacia abajo.","Baja con control en 2-3 segundos. No uses impulso."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'lateral_raise_cable', 'Cable Lateral Raise', 'Elevación Lateral en Polea',
    'upperBody', 'shoulder_side',
    '{"shoulders"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"De pie al lado de la polea baja. Agarra el mango con la mano alejada.","Eleva el brazo al costado hasta la altura del hombro.","Baja lentamente. La polea mantiene tensión incluso en la posición baja."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'machine_lateral_raise', 'Machine Lateral Raise', 'Elevación Lateral en Máquina',
    'upperBody', 'shoulder_side',
    '{"shoulders"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento para que los brazos queden alineados con el pivote.","Empuja los brazos hacia arriba y afuera hasta la altura de los hombros.","Baja con control sin dejar caer el peso. Mayor aislamiento que con mancuernas."}',
    '3', '3', '3-4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'upright_row_barbell', 'Barbell Upright Row', 'Remo al Cuello con Barra',
    'upperBody', 'shoulder_side',
    '{"shoulders"}', '{"back","biceps"}', '{"barbell"}',
    2, 'compound', 1.6, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"Agarra la barra con agarre prono al ancho de hombros o más estrecho.","Jala la barra hacia arriba a lo largo del cuerpo hasta la altura del pecho.","Los codos deben ir por encima de la barra. Baja con control."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    90, 75, 60
  ),
  (
    'rear_delt_fly_dumbbell', 'Rear Delt Fly', 'Apertura de Deltoides Posterior con Mancuernas',
    'upperBody', 'shoulder_rear',
    '{"shoulders"}', '{"back"}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"De pie o sentado, inclina el torso a 45-90°. Mancuernas colgando.","Eleva los brazos hacia los lados y arriba hasta la altura de los hombros.","Aprieta los deltoides posteriores al máximo. Baja lentamente."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'rear_delt_fly_machine', 'Pec Deck Rear Delt', 'Apertura Posterior en Contractora',
    'upperBody', 'shoulder_rear',
    '{"shoulders"}', '{"back"}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate de frente al respaldo de la contractora. Agarra las asas externas.","Abre los brazos hacia atrás apretando el deltoides posterior.","Regresa con control. Mayor aislamiento que con mancuernas."}',
    '3', '3', '3-4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'face_pull_shoulder', 'Face Pull (Rear Delt Focus)', 'Face Pull (Foco Posterior)',
    'upperBody', 'shoulder_rear',
    '{"shoulders"}', '{"back"}', '{"cable"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea a la altura de los ojos. Cuerda con agarre neutro.","Jala hacia la cara separando manos y llevando codos afuera a 90°.","Mantén el pecho afuera y aprieta los deltoides posteriores."}',
    '3', '3-4', '4',
    '15-20', '15-20', '15-20',
    60, 60, 45
  ),
  (
    'bent_over_lateral_raise', 'Bent Over Lateral Raise', 'Elevación Lateral Inclinada',
    'upperBody', 'shoulder_rear',
    '{"shoulders"}', '{"back"}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    '{"Sentado al borde del banco, inclina el torso al frente hasta paralelo al suelo.","Eleva las mancuernas hacia los lados con codos ligeramente flexionados.","Aprieta arriba y baja lentamente. No uses el torso para ayudarte."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'reverse_fly_cable', 'Reverse Cable Fly', 'Apertura Inversa en Poleas',
    'upperBody', 'shoulder_rear',
    '{"shoulders"}', '{"back"}', '{"cable"}',
    2, 'isolation', 1.2, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Cruza los cables (polea derecha para mano izquierda y viceversa).","De pie en el centro. Abre los brazos hacia afuera en arco.","Aprieta los deltoides posteriores y romboides al final. Regresa con control."}',
    '3', '3-4', '4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'squat_barbell', 'Barbell Back Squat', 'Sentadilla con Barra',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes","hamstrings"}', '{"barbell"}',
    2, 'compound', 2, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Barra en la nuca, pies al ancho de hombros o ligeramente más abiertos.","Baja empujando rodillas afuera y cadera hacia atrás hasta muslos paralelos al suelo.","Empuja el suelo con los pies para subir. Mantén el pecho arriba en todo momento."}',
    '3', '4', '4-5',
    '8-10', '6-10', '4-8',
    150, 120, 90
  ),
  (
    'squat_goblet', 'Goblet Squat', 'Sentadilla Goblet',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes","core"}', '{"dumbbell","kettlebell"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Sostén la mancuerna o kettlebell vertical frente al pecho con ambas manos.","Pies al ancho de hombros o algo más. Baja hasta profundidad máxima.","El peso al frente favorece el torso erguido. Empuja hacia arriba."}',
    '3', '3-4', '4',
    '10-15', '10-15', '12-15',
    90, 75, 60
  ),
  (
    'leg_press', 'Leg Press', 'Prensa de Piernas',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes","hamstrings"}', '{"machine"}',
    1, 'compound', 1.8, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Pies al ancho de hombros en la plataforma. Ajusta el asiento para rodillas a 90°.","Empuja la plataforma hasta casi extender las rodillas (no bloquees).","Baja con control hasta que los muslos queden paralelos o más abajo."}',
    '3', '4', '4-5',
    '10-12', '8-12', '8-12',
    120, 90, 75
  ),
  (
    'leg_extension', 'Leg Extension', 'Extensión de Pierna en Máquina',
    'lowerBody', 'quad',
    '{"quads"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el rodillo para que quede en los tobillos. Espalda recta contra el respaldo.","Extiende las piernas hasta arriba apretando el cuádriceps al final.","Baja con control en 2-3 segundos. No dejes caer el peso."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'hack_squat', 'Hack Squat Machine', 'Hack Squat en Máquina',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes"}', '{"machine"}',
    2, 'compound', 1.8, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Espalda y hombros contra los pads. Pies ligeramente adelantados.","Baja hasta que los muslos queden paralelos al suelo o más abajo.","Empuja hacia arriba explosivamente. Gran sobrecarga del cuádriceps."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    120, 90, 75
  ),
  (
    'bulgarian_split_squat', 'Bulgarian Split Squat', 'Sentadilla Búlgara',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes","hamstrings"}', '{"dumbbell","bench"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Pie trasero en el banco. Pie delantero adelantado lo suficiente para alineación de rodilla.","Baja la rodilla trasera hacia el suelo manteniendo el torso erguido.","Empuja desde el talón del pie delantero para subir. Glúteo y cuádriceps."}',
    '3', '3-4', '4',
    '8-10 c/u', '8-12 c/u', '8-12 c/u',
    120, 90, 75
  ),
  (
    'lunge_dumbbell', 'Dumbbell Walking Lunge', 'Zancadas con Mancuernas',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes","hamstrings"}', '{"dumbbell"}',
    1, 'compound', 1.7, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"De pie con mancuernas a los lados. Da un paso largo hacia adelante.","Baja la rodilla trasera casi al suelo manteniendo el torso erguido.","Empuja hacia adelante con el pie delantero y alterna la pierna."}',
    '3', '3-4', '4',
    '10 c/u', '12 c/u', '12-15 c/u',
    90, 75, 60
  ),
  (
    'bodyweight_squat', 'Bodyweight Squat', 'Sentadilla con Peso Corporal',
    'lowerBody', 'quad',
    '{"quads"}', '{"glutes"}', '{"bodyweight"}',
    1, 'compound', 1.3, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Pies al ancho de hombros. Brazos al frente para equilibrio.","Baja empujando caderas hacia atrás y rodillas hacia afuera hasta paralelo.","Empuja hacia arriba apretando glúteos en la posición alta."}',
    '3', '3-4', '4',
    '15-20', '20-30', '30-50',
    75, 60, 45
  ),
  (
    'romanian_deadlift_barbell', 'Romanian Deadlift', 'Peso Muerto Rumano con Barra',
    'lowerBody', 'hamstring',
    '{"hamstrings"}', '{"glutes","back"}', '{"barbell"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"De pie con barra frente a los muslos. Rodillas ligeramente flexionadas.","Inclina el torso hacia adelante empujando las caderas atrás. Espalda recta.","Siente el estiramiento en los isquiotibiales. Regresa apretando glúteos."}',
    '3', '4', '4-5',
    '10-12', '8-12', '6-10',
    120, 90, 75
  ),
  (
    'romanian_deadlift_dumbbell', 'Dumbbell Romanian Deadlift', 'Peso Muerto Rumano con Mancuernas',
    'lowerBody', 'hamstring',
    '{"hamstrings"}', '{"glutes","back"}', '{"dumbbell"}',
    1, 'compound', 1.7, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"De pie con mancuernas frente a los muslos. Mayor rango de movimiento que con barra.","Inclina el torso hacia adelante deslizando las mancuernas por las piernas.","Regresa a posición erguida apretando isquiotibiales y glúteos."}',
    '3', '3-4', '4',
    '10-12', '10-12', '8-12',
    90, 75, 60
  ),
  (
    'leg_curl_lying', 'Lying Leg Curl', 'Curl de Pierna Acostado',
    'lowerBody', 'hamstring',
    '{"hamstrings"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Boca abajo en la máquina. Rodillo en la parte baja de los tobillos.","Curva las piernas llevando los talones hacia los glúteos. Aprieta arriba.","Baja con control en 2-3 segundos. No dejes caer el peso."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'leg_curl_seated', 'Seated Leg Curl', 'Curl de Pierna Sentado',
    'lowerBody', 'hamstring',
    '{"hamstrings"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el respaldo y el rodillo superior sobre los muslos.","Lleva los pies hacia atrás bajo el asiento apretando los isquiotibiales.","Regresa con control. La posición sentada ofrece mayor rango en el bíceps femoral."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'nordic_curl', 'Nordic Curl', 'Curl Nórdico',
    'lowerBody', 'hamstring',
    '{"hamstrings"}', '{}', '{"bodyweight"}',
    3, 'isolation', 1.5, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Arrodíllate y asegura los tobillos bajo algo fijo. Cuerpo erguido.","Baja el torso hacia el suelo lo más lento posible resistiendo con los isquiotibiales.","Usa las manos para apoyarte abajo y regresa contrayendo los isquiotibiales."}',
    '2-3', '3', '3-4',
    '3-5', '5-8', '8-10',
    120, 90, 75
  ),
  (
    'hip_thrust_barbell', 'Barbell Hip Thrust', 'Hip Thrust con Barra',
    'lowerBody', 'glute',
    '{"glutes"}', '{"hamstrings"}', '{"barbell","bench"}',
    2, 'compound', 1.9, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Espalda alta apoyada en el banco. Barra sobre las caderas con almohadilla.","Empuja las caderas hacia arriba apretando fuerte los glúteos arriba.","Mantén 1-2 segundos en la cima. Baja con control hasta casi tocar el suelo."}',
    '3', '4', '4-5',
    '10-12', '8-12', '8-12',
    90, 75, 60
  ),
  (
    'hip_thrust_dumbbell', 'Dumbbell Hip Thrust', 'Hip Thrust con Mancuerna',
    'lowerBody', 'glute',
    '{"glutes"}', '{"hamstrings"}', '{"dumbbell","bench"}',
    1, 'compound', 1.7, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Espalda alta apoyada en el banco. Mancuerna sobre las caderas.","Empuja las caderas arriba apretando los glúteos al máximo.","Pausa 2 segundos arriba. Baja con control hasta casi el suelo."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    90, 75, 60
  ),
  (
    'glute_bridge', 'Glute Bridge', 'Puente de Glúteos',
    'lowerBody', 'glute',
    '{"glutes"}', '{"hamstrings"}', '{"bodyweight"}',
    1, 'compound', 1.3, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Acuéstate boca arriba con rodillas flexionadas y pies apoyados.","Eleva las caderas apretando los glúteos hasta que el cuerpo forme una línea.","Pausa 2 segundos arriba apretando glúteos. Baja con control."}',
    '3', '3-4', '4',
    '15-20', '15-20', '20-25',
    60, 60, 45
  ),
  (
    'cable_kickback', 'Cable Glute Kickback', 'Patada de Glúteo en Polea',
    'lowerBody', 'glute',
    '{"glutes"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Coloca el accesorio en el tobillo. Inclínate ligeramente hacia adelante.","Lleva la pierna hacia atrás y arriba apretando el glúteo al máximo.","Regresa con control. No permitas que la cadera rote."}',
    '3', '3', '3-4',
    '12-15 c/u', '12-15 c/u', '15-20 c/u',
    60, 60, 45
  ),
  (
    'sumo_squat_dumbbell', 'Sumo Squat', 'Sentadilla Sumo con Mancuerna',
    'lowerBody', 'glute',
    '{"glutes"}', '{"quads","adductors"}', '{"dumbbell"}',
    1, 'compound', 1.6, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"Pies más anchos que los hombros, puntas hacia afuera a 45°. Mancuerna entre piernas.","Baja manteniendo el torso erguido y rodillas en línea con los dedos.","Empuja hacia arriba apretando glúteos e internos de muslo en la cima."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    90, 75, 60
  ),
  (
    'calf_raise_standing_machine', 'Standing Calf Raise Machine', 'Elevación de Pantorrillas en Máquina',
    'lowerBody', 'calf',
    '{"calves"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Coloca los hombros bajo los pads. Pies en el borde de la plataforma.","Eleva los talones lo más alto posible apretando las pantorrillas.","Baja lentamente por debajo del nivel de la plataforma para estirar."}',
    '3', '4', '4-5',
    '15-20', '12-15', '10-12',
    75, 60, 60
  ),
  (
    'calf_raise_seated', 'Seated Calf Raise', 'Elevación de Pantorrillas Sentado',
    'lowerBody', 'calf',
    '{"calves"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Rodillas bajo el pad. Pies en el borde de la plataforma.","Eleva los talones lo más posible. La posición sentada activa más el sóleo.","Baja hasta estiramiento máximo. Pausa 1 segundo abajo."}',
    '3', '3-4', '4',
    '15-20', '15-20', '12-15',
    60, 60, 45
  ),
  (
    'calf_raise_bodyweight', 'Bodyweight Calf Raise', 'Elevación de Pantorrillas con Peso Corporal',
    'lowerBody', 'calf',
    '{"calves"}', '{}', '{"bodyweight"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"De pie en un escalón o borde. Solo la parte delantera del pie apoyada.","Eleva los talones lo más alto posible. Pausa 2 segundos arriba.","Baja controlado por debajo del nivel del escalón para máximo estiramiento."}',
    '3', '3-4', '4',
    '15-20', '20-30', '30-50',
    60, 60, 45
  ),
  (
    'calf_raise_leg_press', 'Leg Press Calf Raise', 'Elevación de Pantorrilla en Prensa',
    'lowerBody', 'calf',
    '{"calves"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"En la prensa, coloca solo la punta de los pies en el borde de la plataforma.","Extiende los tobillos empujando la plataforma con los dedos del pie.","Regresa con control hasta estiramiento completo."}',
    '3', '3-4', '4',
    '15-20', '15-20', '12-15',
    60, 60, 45
  ),
  (
    'machine_adduction', 'Inner Thigh Machine', 'Aducción en Máquina',
    'lowerBody', 'adductor',
    '{"adductors"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Siéntate con piernas separadas sobre los pads exteriores.","Cierra las piernas resistiendo el peso. Aprieta los aductores.","Regresa lentamente con control. Mantén la espalda recta."}',
    '3', '3', '3-4',
    '12-15', '12-15', '12-15',
    60, 60, 45
  ),
  (
    'cable_adduction', 'Cable Hip Adduction', 'Aducción de Cadera en Polea',
    'lowerBody', 'adductor',
    '{"adductors"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Accesorio en tobillo lateral. De pie con la polea al costado.","Cruza la pierna hacia adelante del cuerpo activando los aductores.","Regresa con control manteniendo el balance sobre una pierna."}',
    '3', '3', '3-4',
    '12-15 c/u', '12-15 c/u', '15-20 c/u',
    60, 60, 45
  ),
  (
    'lateral_lunge', 'Lateral Lunge', 'Zancada Lateral',
    'lowerBody', 'adductor',
    '{"adductors"}', '{"glutes","quads"}', '{"bodyweight"}',
    1, 'compound', 1.4, 'https://images.unsplash.com/photo-1434608519344-49d77a124f90?w=600&q=80&fit=crop',
    '{"De pie. Da un paso amplio hacia el costado. Pierna de apoyo recta.","Dobla la rodilla de la pierna que da el paso empujando la cadera atrás.","Regresa empujando desde el talón. Activa aductores e isquio al subir."}',
    '3', '3-4', '4',
    '10 c/u', '12 c/u', '12-15 c/u',
    75, 60, 60
  ),
  (
    'barbell_curl', 'Barbell Bicep Curl', 'Curl de Bíceps con Barra',
    'upperBody', 'bicep',
    '{"biceps"}', '{"forearms"}', '{"barbell"}',
    1, 'isolation', 1.3, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"De pie con barra en agarre supino al ancho de hombros. Codos pegados al cuerpo.","Curva los antebrazos hacia los hombros apretando el bíceps al máximo.","Baja con control en 2-3 segundos. No balancees el torso."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    75, 60, 60
  ),
  (
    'dumbbell_curl', 'Dumbbell Bicep Curl', 'Curl de Bíceps con Mancuernas',
    'upperBody', 'bicep',
    '{"biceps"}', '{"forearms"}', '{"dumbbell"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"De pie con mancuernas a los lados. Codos pegados al cuerpo.","Curva los brazos supinando la muñeca al subir (palma hacia arriba al final).","Baja con control. Alterna o ambos brazos simultáneamente."}',
    '3', '3-4', '4',
    '10-12', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'hammer_curl', 'Hammer Curl', 'Curl Martillo',
    'upperBody', 'bicep',
    '{"biceps"}', '{"forearms"}', '{"dumbbell"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Mancuernas con agarre neutro (palmas enfrentadas). Posición de martillo.","Curva los brazos manteniendo el agarre neutro. Activa el braquial.","Baja con control. Trabaja el braquial y braquirradial además del bíceps."}',
    '3', '3-4', '4',
    '10-12', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'preacher_curl', 'Preacher Curl', 'Curl en Predicador',
    'upperBody', 'bicep',
    '{"biceps"}', '{}', '{"barbell","machine"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Apoya los brazos en el pad del predicador. Barra o mancuerna en manos.","Baja los brazos hasta extensión casi completa. No hiperextiendas.","Curva apretando el bíceps al máximo. Mayor aislamiento por la fijación."}',
    '3', '3-4', '4',
    '10-12', '8-12', '8-10',
    75, 60, 60
  ),
  (
    'cable_curl', 'Cable Curl', 'Curl en Polea',
    'upperBody', 'bicep',
    '{"biceps"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea baja con barra recta o EZ. Codos pegados al cuerpo.","Curva los brazos manteniendo tensión constante de la polea.","La polea mantiene más tensión en la posición baja vs. mancuernas."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    60, 60, 45
  ),
  (
    'incline_dumbbell_curl', 'Incline Dumbbell Curl', 'Curl Inclinado con Mancuernas',
    'upperBody', 'bicep',
    '{"biceps"}', '{}', '{"dumbbell","bench"}',
    2, 'isolation', 1.2, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Banco inclinado a 45-60°. Brazos colgando rectos hacia abajo.","Curva los brazos supinando la muñeca. Mayor estiramiento del bíceps largo.","Baja completamente. La posición inclinada maximiza el rango de estiramiento."}',
    '3', '3-4', '4',
    '10-12', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'concentration_curl', 'Concentration Curl', 'Curl de Concentración',
    'upperBody', 'bicep',
    '{"biceps"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Sentado, codo apoyado en el interior del muslo. Mancuerna colgando.","Curva el brazo girando la muñeca. Máxima contracción arriba.","Baja con control. Excelente pico de bíceps."}',
    '3', '3', '3-4',
    '12-15 c/u', '10-12 c/u', '10-12 c/u',
    60, 60, 45
  ),
  (
    'machine_curl', 'Machine Curl', 'Curl en Máquina',
    'upperBody', 'bicep',
    '{"biceps"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta el asiento para que los codos queden alineados con el pivote.","Curva los brazos hasta la contracción máxima. Pausa 1 segundo.","Baja con control. Ideal para sobrecarga progresiva con control."}',
    '3', '3', '3-4',
    '12-15', '10-12', '10-12',
    60, 60, 45
  ),
  (
    'tricep_dip_bench', 'Bench Dip', 'Fondos en Banco para Tríceps',
    'upperBody', 'tricep',
    '{"triceps"}', '{"shoulders"}', '{"bench","bodyweight"}',
    1, 'compound', 1.5, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Manos en el borde del banco, pies extendidos al frente.","Baja el cuerpo flexionando codos hasta 90°. Mantenlos hacia atrás.","Empuja hacia arriba extendiendo los codos. No bloquees completamente."}',
    '3', '3-4', '4',
    '10-12', '12-15', '15-20',
    90, 75, 60
  ),
  (
    'close_grip_bench_press', 'Close Grip Bench Press', 'Press de Banca Agarre Cerrado',
    'upperBody', 'tricep',
    '{"triceps"}', '{"chest","shoulders"}', '{"barbell","bench"}',
    2, 'compound', 1.8, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Agarra la barra algo más estrecho que los hombros. No demasiado cerrado.","Baja la barra al pecho con codos pegados al cuerpo (45°).","Empuja explosivamente. Activa principalmente los tríceps."}',
    '3', '4', '4-5',
    '8-10', '6-10', '6-8',
    120, 90, 75
  ),
  (
    'tricep_pushdown_cable', 'Tricep Pushdown', 'Extensión de Tríceps en Polea',
    'upperBody', 'tricep',
    '{"triceps"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea alta. Agarra la barra o cuerda con codos pegados al cuerpo.","Extiende los brazos hacia abajo hasta extensión completa. Aprieta el tríceps.","Regresa con control hasta codos a 90°. No muevas los codos."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    60, 60, 45
  ),
  (
    'skullcrusher', 'Skull Crusher', 'Rompecráneos con Barra',
    'upperBody', 'tricep',
    '{"triceps"}', '{}', '{"barbell","bench"}',
    2, 'isolation', 1.3, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Acuéstate en banco. Brazos extendidos sobre el pecho sosteniendo la barra.","Flexiona los codos bajando la barra hacia la frente. Codos fijos.","Extiende los codos regresando arriba. Máximo aislamiento del tríceps."}',
    '3', '3-4', '4',
    '10-12', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'overhead_tricep_dumbbell', 'Overhead Tricep Extension', 'Extensión de Tríceps sobre la Cabeza',
    'upperBody', 'tricep',
    '{"triceps"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Sentado o de pie. Sostén la mancuerna sobre la cabeza con ambas manos.","Baja la mancuerna detrás de la cabeza flexionando los codos. Codos fijos.","Extiende los codos hacia arriba apretando el tríceps. Mayor activación de la cabeza larga."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    75, 60, 60
  ),
  (
    'tricep_kickback', 'Tricep Kickback', 'Extensión de Tríceps en Patada',
    'upperBody', 'tricep',
    '{"triceps"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Inclina el torso a 45-90°. Codo fijo al lado del cuerpo a 90°.","Extiende el brazo hacia atrás hasta extensión completa del codo.","Regresa con control. Mantén el codo fijo durante todo el movimiento."}',
    '3', '3', '3-4',
    '12-15 c/u', '12-15 c/u', '12-15 c/u',
    60, 60, 45
  ),
  (
    'diamond_push_up', 'Diamond Push Up', 'Flexión Diamante',
    'upperBody', 'tricep',
    '{"triceps"}', '{"chest"}', '{"bodyweight"}',
    2, 'compound', 1.5, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Manos formando un triángulo (diamante) bajo el pecho. Pulgares e índices se tocan.","Baja el pecho hacia las manos manteniendo los codos cerca del cuerpo.","Empuja hacia arriba apretando los tríceps. Mayor activación que push up normal."}',
    '3', '3-4', '4',
    '6-10', '10-15', '15-20',
    90, 75, 60
  ),
  (
    'cable_overhead_tricep', 'Cable Overhead Tricep Extension', 'Extensión de Tríceps sobre la Cabeza en Polea',
    'upperBody', 'tricep',
    '{"triceps"}', '{}', '{"cable"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea alta con cuerda. De espaldas a la máquina, inclínate ligeramente.","Lleva la cuerda hacia adelante extendiendo los codos frente a ti.","Regresa con control. La polea mantiene tensión en el estiramiento."}',
    '3', '3-4', '4',
    '12-15', '10-12', '10-12',
    60, 60, 45
  ),
  (
    'wrist_curl_dumbbell', 'Wrist Curl', 'Curl de Muñeca con Mancuerna',
    'upperBody', 'forearm',
    '{"forearms"}', '{}', '{"dumbbell"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Sentado, antebrazo sobre el muslo con la muñeca fuera del borde. Palma arriba.","Baja la mancuerna arqueando la muñeca hacia abajo.","Sube apretando los flexores del antebrazo al máximo."}',
    '3', '3', '3-4',
    '15-20', '15-20', '15-20',
    60, 45, 45
  ),
  (
    'reverse_wrist_curl', 'Reverse Wrist Curl', 'Curl Inverso de Muñeca',
    'upperBody', 'forearm',
    '{"forearms"}', '{}', '{"barbell"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Antebrazo sobre el muslo, palma hacia abajo. Barra o mancuerna en mano.","Extiende la muñeca hacia arriba. Trabaja los extensores del antebrazo.","Baja con control. Complementa el curl de muñeca regular."}',
    '3', '3', '3',
    '15-20', '15-20', '15-20',
    60, 45, 45
  ),
  (
    'farmer_carry', 'Farmer Carry', 'Caminata del Granjero',
    'upperBody', 'forearm',
    '{"forearms"}', '{"shoulders","core","back"}', '{"dumbbell"}',
    1, 'compound', 1.4, 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80&fit=crop',
    '{"Sostén mancuernas pesadas a los lados. Torso erguido, hombros atrás.","Camina a paso controlado por 20-40 metros.","Desarrolla fuerza de agarre y resistencia del antebrazo funcionalmente."}',
    '3', '3-4', '4',
    '20m', '30m', '40m',
    90, 75, 60
  ),
  (
    'crunch', 'Crunch', 'Crunch Abdominal',
    'core', 'abs',
    '{"abs"}', '{}', '{"bodyweight"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Acuéstate boca arriba. Rodillas flexionadas, pies apoyados. Manos en la nuca.","Eleva solo los hombros del suelo apretando el abdomen. No jales el cuello.","Baja con control sin que la cabeza toque el suelo entre repeticiones."}',
    '3', '3-4', '4',
    '15-20', '20-25', '25-30',
    60, 45, 45
  ),
  (
    'cable_crunch', 'Cable Crunch', 'Crunch en Polea',
    'core', 'abs',
    '{"abs"}', '{}', '{"cable"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Arrodíllate frente a la polea alta. Agarra la cuerda detrás de la cabeza.","Flexiona el torso hacia abajo apretando el abdomen. Caderas fijas.","Regresa con control. Permite sobrecarga progresiva a diferencia del crunch normal."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'hanging_leg_raise', 'Hanging Leg Raise', 'Elevación de Piernas Colgado',
    'core', 'abs',
    '{"abs"}', '{"hip_flexors"}', '{"pullup_bar","bodyweight"}',
    2, 'isolation', 1.4, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Cuelga de la barra con agarre prono. Evita balancearte.","Eleva las piernas hasta que queden paralelas al suelo (o más). Aprieta el abdomen.","Baja con control. Curvea la pelvis al subir para mayor activación abdominal."}',
    '3', '3-4', '4',
    '8-10', '10-12', '12-15',
    75, 60, 60
  ),
  (
    'plank', 'Plank', 'Plancha Abdominal',
    'core', 'abs',
    '{"abs"}', '{"shoulders","glutes"}', '{"bodyweight"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Posición de plancha sobre antebrazos. Cuerpo recto de cabeza a talones.","Aprieta abdomen, glúteos y cuádriceps. No dejes caer la cadera.","Mantén la posición el tiempo objetivo. Respira normalmente."}',
    '3', '3-4', '4',
    '20-30 seg', '30-60 seg', '60-90 seg',
    60, 60, 45
  ),
  (
    'ab_wheel_rollout', 'Ab Wheel Rollout', 'Rodillo Abdominal',
    'core', 'abs',
    '{"abs"}', '{"back","shoulders"}', '{"bodyweight"}',
    3, 'compound', 1.6, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Arrodíllado con el rodillo bajo los hombros. Espalda recta.","Extiende el cuerpo hacia adelante rodando lentamente. Abdomen activado.","Regresa jalando con el abdomen. Uno de los mejores ejercicios de core."}',
    '2-3', '3', '3-4',
    '5-8', '8-12', '12-15',
    90, 75, 60
  ),
  (
    'sit_up', 'Sit Up', 'Abdominales Completos',
    'core', 'abs',
    '{"abs"}', '{"hip_flexors"}', '{"bodyweight"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Acuéstate boca arriba con rodillas flexionadas. Manos cruzadas en el pecho.","Sube el torso hasta quedar sentado usando el abdomen. No el cuello.","Baja con control hasta que la espalda casi toque el suelo."}',
    '3', '3-4', '4',
    '15-20', '20-25', '25-30',
    60, 45, 45
  ),
  (
    'v_up', 'V-Up', 'Elevación en V',
    'core', 'abs',
    '{"abs"}', '{"hip_flexors"}', '{"bodyweight"}',
    2, 'isolation', 1.3, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Acuéstate con brazos extendidos sobre la cabeza y piernas rectas.","Eleva simultáneamente el torso y las piernas formando una \"V\".","Baja con control sin que piernas ni brazos toquen el suelo entre reps."}',
    '3', '3-4', '4',
    '8-12', '12-15', '15-20',
    75, 60, 60
  ),
  (
    'machine_crunch', 'Machine Crunch', 'Crunch en Máquina',
    'core', 'abs',
    '{"abs"}', '{}', '{"machine"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Ajusta los pads a la altura del pecho. Siéntate con pies asegurados.","Flexiona el torso hacia adelante apretando el abdomen al máximo.","Regresa con control. Permite sobrecarga progresiva constante."}',
    '3', '3-4', '4',
    '12-15', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'russian_twist', 'Russian Twist', 'Giro Ruso',
    'core', 'obliques',
    '{"obliques"}', '{"abs"}', '{"bodyweight"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Sentado con torso a 45°, pies elevados. Manos juntas frente al pecho.","Gira el torso de lado a lado tocando el suelo junto a las caderas.","Para más difícil: sostén un disco o mancuerna. Mantén el pecho alto."}',
    '3', '3-4', '4',
    '20 (10c/u)', '30 (15c/u)', '40 (20c/u)',
    60, 45, 45
  ),
  (
    'side_plank', 'Side Plank', 'Plancha Lateral',
    'core', 'obliques',
    '{"obliques"}', '{"abs","glutes"}', '{"bodyweight"}',
    1, 'isolation', 1.2, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Apoya un antebrazo en el suelo. Cuerpo en línea recta lateral.","Eleva las caderas del suelo. Aprieta oblicuos y glúteos.","Mantén la posición. Cambia de lado después del tiempo objetivo."}',
    '3 c/u', '3-4 c/u', '4 c/u',
    '20-30 seg', '30-45 seg', '45-60 seg',
    60, 45, 45
  ),
  (
    'cable_woodchop', 'Cable Woodchop', 'Leñador en Polea',
    'core', 'obliques',
    '{"obliques"}', '{"abs","shoulders"}', '{"cable"}',
    2, 'compound', 1.3, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Polea alta al costado. Agarra el mango con ambas manos. Pies al ancho de hombros.","Gira el torso jalando la polea hacia abajo y al frente en diagonal.","Regresa controlado a la posición inicial. Trabaja la cadena de rotación."}',
    '3', '3-4', '4',
    '10-12 c/u', '12-15 c/u', '12-15 c/u',
    75, 60, 60
  ),
  (
    'oblique_crunch', 'Oblique Crunch', 'Crunch Oblicuo',
    'core', 'obliques',
    '{"obliques"}', '{"abs"}', '{"bodyweight"}',
    1, 'isolation', 1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Acuéstate con rodillas a un lado (o cruza una pierna). Manos en la nuca.","Eleva el hombro opuesto hacia las rodillas rotando el torso.","Siente la contracción en el oblicuo. Baja con control y cambia de lado."}',
    '3', '3-4', '4',
    '12-15 c/u', '15-20 c/u', '20-25 c/u',
    60, 45, 45
  ),
  (
    'bicycle_crunch', 'Bicycle Crunch', 'Crunch de Bicicleta',
    'core', 'obliques',
    '{"obliques"}', '{"abs"}', '{"bodyweight"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Acuéstate boca arriba. Manos en la nuca, piernas levantadas a 45°.","Lleva el codo derecho hacia la rodilla izquierda y viceversa alternando.","Mueve las piernas simulando el pedaleo. Activación alta de oblicuos."}',
    '3', '3-4', '4',
    '20 (10c/u)', '30 (15c/u)', '40 (20c/u)',
    60, 45, 45
  ),
  (
    'hyperextension_back', 'Hyperextension', 'Hiperextensión Lumbar',
    'core', 'lower_back',
    '{"lower_back"}', '{"glutes","hamstrings"}', '{"bodyweight"}',
    1, 'isolation', 1.3, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"Posiciona las caderas en el borde del banco GHD. Pies asegurados.","Baja el torso hacia el suelo manteniendo la espalda neutra.","Eleva hasta que el cuerpo forme una línea recta. Aprieta glúteos arriba."}',
    '3', '3-4', '4',
    '12-15', '15-20', '15-20',
    75, 60, 60
  ),
  (
    'superman_back', 'Superman Hold', 'Superman',
    'core', 'lower_back',
    '{"lower_back"}', '{"glutes"}', '{"bodyweight"}',
    1, 'isolation', 1.1, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"Boca abajo con brazos extendidos al frente. Piernas rectas.","Eleva brazos, pecho y piernas simultáneamente del suelo.","Pausa 2-3 segundos en la posición alta. Baja con control."}',
    '3', '3', '3-4',
    '10-12', '12-15', '15-20',
    60, 60, 45
  ),
  (
    'bird_dog', 'Bird Dog', 'Perro Pájaro',
    'core', 'lower_back',
    '{"lower_back"}', '{"abs","glutes"}', '{"bodyweight"}',
    1, 'compound', 1.2, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&fit=crop',
    '{"A cuatro patas con espalda recta. Manos bajo hombros, rodillas bajo caderas.","Extiende el brazo derecho y la pierna izquierda simultáneamente. Pausa 2 seg.","Regresa y alterna. Activa músculos estabilizadores profundos de la columna."}',
    '3', '3', '3-4',
    '8 c/u', '10 c/u', '12 c/u',
    60, 60, 45
  ),
  (
    'cable_pull_through', 'Cable Pull Through', 'Tirón en Polea entre Piernas',
    'core', 'lower_back',
    '{"lower_back"}', '{"glutes","hamstrings"}', '{"cable"}',
    1, 'compound', 1.4, 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    '{"De espaldas a la polea baja. Agarra la cuerda entre las piernas.","Inclina el torso hacia adelante empujando las caderas atrás.","Regresa a posición erguida apretando glúteos y lumbar. Similar al peso muerto."}',
    '3', '3-4', '4',
    '12-15', '12-15', '12-15',
    75, 60, 60
  )
;

-- Total: 120 exercises
