import type { Exercise } from '../types'

// ─── Exercise Database ─────────────────────────────────────────────────────────
// Each exercise has weights/tags that the scoring algorithm uses to match
// against the user's WeightMap.

export const EXERCISES: Exercise[] = [
  // ═══════════════════════════════════
  // UPPER BODY — Compound
  // ═══════════════════════════════════
  {
    id: 'bench_press_barbell',
    name: 'Barbell Bench Press',
    nameEs: 'Press de Banca con Barra',
    muscleGroup: 'upperBody',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 2.0,
    image: 'https://images.unsplash.com/photo-1534368420009-621bfab424a8?w=600&q=80&fit=crop',
    instructions: [
      'Acuéstate en el banco con los pies apoyados en el suelo.',
      'Agarra la barra con las manos a la anchura de los hombros.',
      'Baja la barra controladamente hasta el pecho.',
      'Empuja hacia arriba explosivamente hasta extender los brazos.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '5' },
    reps:  { beginner: '8-10', intermediate: '8-12', advanced: '6-10' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    nameEs: 'Press Inclinado con Mancuernas',
    muscleGroup: 'upperBody',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 1.8,
    image: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    instructions: [
      'Ajusta el banco a 30-45 grados.',
      'Sostén las mancuernas a la altura del pecho.',
      'Empuja hacia arriba y adentro hasta que las mancuernas casi se toquen.',
      'Baja con control en 2-3 segundos.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    nameEs: 'Press Militar con Barra',
    muscleGroup: 'upperBody',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['barbell'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 1.9,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    instructions: [
      'De pie, agarra la barra a la anchura de los hombros.',
      'Empuja la barra hacia arriba mientras echas la cabeza hacia atrás ligeramente.',
      'Extiende completamente los brazos en la parte superior.',
      'Baja con control hasta el nivel de la clavícula.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '8-10', intermediate: '6-10', advanced: '5-8' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'pull_up',
    name: 'Pull Up',
    nameEs: 'Dominadas',
    muscleGroup: 'upperBody',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: ['pullup_bar'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 2.0,
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a78?w=600&q=80&fit=crop',
    instructions: [
      'Cuelga de la barra con agarre prono, manos separadas más que los hombros.',
      'Activa el core y tira con los codos hacia abajo y atrás.',
      'Sube hasta que el mentón supere la barra.',
      'Baja con control total.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '5-8', intermediate: '8-12', advanced: '10-15' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'barbell_row',
    name: 'Barbell Bent-Over Row',
    nameEs: 'Remo con Barra',
    muscleGroup: 'upperBody',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders', 'forearms'],
    equipment: ['barbell'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 1.9,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80&fit=crop',
    instructions: [
      'Inclínate hacia adelante con la espalda recta a 45 grados.',
      'Agarra la barra con agarre prono a la anchura de los hombros.',
      'Tira de la barra hacia el ombligo apretando los omóplatos.',
      'Baja con control total.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '8-10', intermediate: '8-12', advanced: '6-10' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    nameEs: 'Press de Hombros con Mancuernas',
    muscleGroup: 'upperBody',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.7,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    instructions: [
      'Siéntate con la espalda recta, mancuernas a la altura de los hombros.',
      'Empuja hacia arriba hasta extender los brazos.',
      'Baja con control a la posición inicial.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'push_up',
    name: 'Push Up',
    nameEs: 'Flexiones de Brazos',
    muscleGroup: 'upperBody',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.5,
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80&fit=crop',
    instructions: [
      'Posición de plancha alta, manos bajo los hombros.',
      'Baja el cuerpo hasta que el pecho casi toque el suelo.',
      'Empuja hasta extender los brazos.',
      'Mantén el cuerpo como una tabla durante todo el movimiento.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '8-12', intermediate: '12-20', advanced: '20-30' },
    rest:  { beginner: 90, intermediate: 60, advanced: 45 },
  },

  // ═══════════════════════════════════
  // UPPER BODY — Isolation
  // ═══════════════════════════════════
  {
    id: 'bicep_curl_dumbbell',
    name: 'Dumbbell Bicep Curl',
    nameEs: 'Curl de Bíceps con Mancuernas',
    muscleGroup: 'upperBody',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1583454155184-870a1f63aebc?w=600&q=80&fit=crop',
    instructions: [
      'De pie, mancuernas a los lados con agarre supino.',
      'Dobla los codos llevando las mancuernas hacia los hombros.',
      'Aprieta el bíceps en la parte superior.',
      'Baja con control en 2-3 segundos.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10-12', intermediate: '10-15', advanced: '10-15' },
    rest:  { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'tricep_pushdown_cable',
    name: 'Cable Tricep Pushdown',
    nameEs: 'Extensión de Tríceps en Polea',
    muscleGroup: 'upperBody',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1516481157630-05bc0aeb8b19?w=600&q=80&fit=crop',
    instructions: [
      'De pie frente a la polea alta, agarra la barra con agarre prono.',
      'Mantén los codos pegados al cuerpo.',
      'Empuja hacia abajo hasta extender los brazos completamente.',
      'Vuelve a la posición inicial con control.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '12-15', intermediate: '10-15', advanced: '10-15' },
    rest:  { beginner: 60, intermediate: 60, advanced: 45 },
  },
  {
    id: 'lateral_raise',
    name: 'Dumbbell Lateral Raise',
    nameEs: 'Elevaciones Laterales',
    muscleGroup: 'upperBody',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80&fit=crop',
    instructions: [
      'De pie, mancuernas a los lados.',
      'Levanta los brazos lateralmente hasta la altura de los hombros.',
      'Mantén una ligera flexión en los codos.',
      'Baja lentamente.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4-5' },
    reps:  { beginner: '12-15', intermediate: '12-15', advanced: '15-20' },
    rest:  { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    nameEs: 'Face Pull en Polea',
    muscleGroup: 'upperBody',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.1,
    image: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80&fit=crop',
    instructions: [
      'Ajusta la polea a la altura de la cara.',
      'Tira de la cuerda hacia tu cara, separando las manos.',
      'Aprieta los omóplatos al final del movimiento.',
      'Vuelve a la posición inicial con control.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '15', intermediate: '15-20', advanced: '15-20' },
    rest:  { beginner: 60, intermediate: 45, advanced: 45 },
  },

  // ═══════════════════════════════════
  // LOWER BODY — Compound
  // ═══════════════════════════════════
  {
    id: 'barbell_squat',
    name: 'Barbell Back Squat',
    nameEs: 'Sentadilla con Barra',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: ['barbell'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 2.0,
    image: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600&q=80&fit=crop',
    instructions: [
      'Coloca la barra en la parte alta de la espalda.',
      'Pies a la anchura de los hombros, puntas ligeramente hacia afuera.',
      'Baja como si te sentaras en una silla, rodillas sobre los pies.',
      'Sube explosivamente empujando el suelo.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '8-10', intermediate: '6-10', advanced: '5-8' },
    rest:  { beginner: 180, intermediate: 120, advanced: 90 },
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    nameEs: 'Peso Muerto Rumano',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell', 'dumbbell'],
    difficulty: 2,
    type: 'compound',
    compoundBonus: 1.9,
    image: 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=600&q=80&fit=crop',
    instructions: [
      'De pie con la barra o mancuernas frente a ti.',
      'Inclínate hacia adelante manteniendo la espalda recta.',
      'Siente el estiramiento en los isquiotibiales.',
      'Vuelve arriba apretando los glúteos.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10-12', intermediate: '8-12', advanced: '8-10' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    nameEs: 'Hip Thrust con Barra',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    equipment: ['barbell', 'bench'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.8,
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&q=80&fit=crop',
    instructions: [
      'Apoya la parte alta de la espalda en el banco.',
      'Coloca la barra sobre las caderas con amortiguador.',
      'Empuja las caderas hacia arriba hasta alinear rodillas, caderas y hombros.',
      'Aprieta los glúteos en la parte superior por 1 segundo.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4-5' },
    reps:  { beginner: '10-15', intermediate: '8-15', advanced: '8-12' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    nameEs: 'Prensa de Piernas',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.7,
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80&fit=crop',
    instructions: [
      'Siéntate en la prensa con los pies a la anchura de los hombros.',
      'Baja la plataforma hasta que las rodillas formen 90 grados.',
      'Empuja hasta casi extender las piernas (sin bloquear).',
      'Controla el descenso.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10-15', intermediate: '10-15', advanced: '8-12' },
    rest:  { beginner: 120, intermediate: 90, advanced: 75 },
  },
  {
    id: 'walking_lunges',
    name: 'Walking Lunges',
    nameEs: 'Zancadas Caminando',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['bodyweight', 'dumbbell'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.6,
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&q=80&fit=crop',
    instructions: [
      'De pie con los pies juntos.',
      'Da un gran paso hacia adelante y baja la rodilla trasera.',
      'Empuja con el pie delantero para avanzar.',
      'Alterna las piernas en cada paso.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10 c/lado', intermediate: '12-15 c/lado', advanced: '15-20 c/lado' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    nameEs: 'Sentadilla Goblet',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['dumbbell', 'kettlebell'],
    difficulty: 1,
    type: 'compound',
    compoundBonus: 1.5,
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&q=80&fit=crop',
    instructions: [
      'Sostén la mancuerna verticalmente frente al pecho.',
      'Pies a la anchura de los hombros.',
      'Baja en sentadilla profunda con la espalda recta.',
      'Empuja a través de los talones para subir.',
    ],
    sets:  { beginner: '3', intermediate: '3', advanced: '3-4' },
    reps:  { beginner: '10-15', intermediate: '12-15', advanced: '15-20' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
  {
    id: 'calf_raise',
    name: 'Standing Calf Raise',
    nameEs: 'Elevaciones de Pantorrilla',
    muscleGroup: 'lowerBody',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbell', 'machine'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1520334363367-7e01bc1bd2e4?w=600&q=80&fit=crop',
    instructions: [
      'De pie en el borde de un escalón.',
      'Baja los talones por debajo del nivel del escalón.',
      'Sube en punta de pie lo más alto posible.',
      'Sostén 1 segundo arriba.',
    ],
    sets:  { beginner: '3', intermediate: '4', advanced: '4-5' },
    reps:  { beginner: '15-20', intermediate: '15-20', advanced: '20-25' },
    rest:  { beginner: 60, intermediate: 45, advanced: 30 },
  },

  // ═══════════════════════════════════
  // CORE
  // ═══════════════════════════════════
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    nameEs: 'Peso Muerto Convencional',
    muscleGroup: 'core',
    primaryMuscles: ['lowerBack'],
    secondaryMuscles: ['abs', 'obliques'],
    equipment: ['barbell'],
    difficulty: 3,
    type: 'compound',
    compoundBonus: 2.0,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80&fit=crop',
    instructions: [
      'Pies bajo la barra a la anchura de las caderas.',
      'Agarra la barra con las manos fuera de las piernas.',
      'Espalda recta, pecho arriba, caderas hacia abajo.',
      'Empuja el suelo y sube manteniendo la barra pegada al cuerpo.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4-5' },
    reps:  { beginner: '5-8', intermediate: '5-8', advanced: '3-6' },
    rest:  { beginner: 180, intermediate: 150, advanced: 120 },
  },
  {
    id: 'plank',
    name: 'Plank',
    nameEs: 'Plancha Isométrica',
    muscleGroup: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'lowerBack'],
    equipment: ['bodyweight'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80&fit=crop',
    instructions: [
      'Posición de plancha baja sobre los codos.',
      'Cuerpo recto de cabeza a talones.',
      'Activa el core, glúteos y cuádriceps.',
      'Mantén la posición sin arquear la espalda.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '20-30 seg', intermediate: '45-60 seg', advanced: '60-90 seg' },
    rest:  { beginner: 60, intermediate: 45, advanced: 30 },
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    nameEs: 'Elevación de Piernas Colgado',
    muscleGroup: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['pullup_bar'],
    difficulty: 2,
    type: 'isolation',
    compoundBonus: 1.2,
    image: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=600&q=80&fit=crop',
    instructions: [
      'Cuelga de la barra con agarre prono.',
      'Lleva las piernas hacia arriba con las rodillas dobladas (principiante) o rectas (avanzado).',
      'Controla el descenso sin balancearte.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '8-12', intermediate: '12-15', advanced: '15-20' },
    rest:  { beginner: 75, intermediate: 60, advanced: 45 },
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    nameEs: 'Crunch en Polea',
    muscleGroup: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.1,
    image: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=600&q=80&fit=crop',
    instructions: [
      'Arrodíllado frente a la polea alta con cuerda.',
      'Lleva los codos hacia las rodillas doblando la columna.',
      'Aprieta el abdomen en la posición más baja.',
      'Sube con control.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '12-15', intermediate: '15-20', advanced: '15-20' },
    rest:  { beginner: 60, intermediate: 45, advanced: 45 },
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    nameEs: 'Giro Ruso',
    muscleGroup: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs'],
    equipment: ['bodyweight', 'dumbbell'],
    difficulty: 1,
    type: 'isolation',
    compoundBonus: 1.0,
    image: 'https://images.unsplash.com/photo-1520334363367-7e01bc1bd2e4?w=600&q=80&fit=crop',
    instructions: [
      'Siéntate con las rodillas dobladas y los pies elevados.',
      'Inclínate ligeramente hacia atrás.',
      'Gira el torso de lado a lado con control.',
      'Opcional: sostén una mancuerna para mayor resistencia.',
    ],
    sets:  { beginner: '3', intermediate: '3-4', advanced: '4' },
    reps:  { beginner: '10 c/lado', intermediate: '15 c/lado', advanced: '20 c/lado' },
    rest:  { beginner: 60, intermediate: 45, advanced: 30 },
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    nameEs: 'Rueda Abdominal',
    muscleGroup: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lowerBack', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 3,
    type: 'compound',
    compoundBonus: 1.5,
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80&fit=crop',
    instructions: [
      'De rodillas con la rueda abdominal en el suelo.',
      'Rueda hacia adelante manteniendo el core apretado.',
      'Llega lo más lejos posible sin arquear la espalda.',
      'Regresa a la posición inicial con el core activo.',
    ],
    sets:  { beginner: '2-3', intermediate: '3', advanced: '3-4' },
    reps:  { beginner: '5-8', intermediate: '8-12', advanced: '12-15' },
    rest:  { beginner: 90, intermediate: 75, advanced: 60 },
  },
]

// ─── Equipment availability map ───────────────────────────────────────────────
export const EQUIPMENT_AVAILABILITY: Record<string, string[]> = {
  full_gym:    ['barbell', 'dumbbell', 'machine', 'cable', 'pullup_bar', 'bench', 'kettlebell', 'bodyweight'],
  home_gym:    ['dumbbell', 'pullup_bar', 'bench', 'kettlebell', 'bodyweight'],
  bodyweight:  ['bodyweight', 'pullup_bar'],
}
