/**
 * Generates supabase/exercises_seed.sql from the TypeScript exercise bank.
 * Run: npx tsx scripts/generate-exercises-sql.ts > supabase/exercises_seed.sql
 */
import { EXERCISES } from '../src/constants/exerciseBank/index'

function pgArray(arr: string[]): string {
  if (!arr.length) return "'{}'"
  const escaped = arr.map(s => `"${s.replace(/"/g, '\\"')}"`)
  return `'{${escaped.join(',')}}'`
}

function pgText(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

const lines: string[] = [
  '-- ============================================================',
  '-- LIFEFYT — Exercise Bank Seed',
  '-- Auto-generated by scripts/generate-exercises-sql.ts',
  '-- Run AFTER exercises_schema.sql',
  '-- ============================================================',
  '',
  'INSERT INTO exercises (',
  '  id, name, name_es,',
  '  muscle_group, muscle_target,',
  '  primary_muscles, secondary_muscles, equipment,',
  '  difficulty, type, compound_bonus, image,',
  '  instructions,',
  '  sets_beginner, sets_intermediate, sets_advanced,',
  '  reps_beginner, reps_intermediate, reps_advanced,',
  '  rest_beginner, rest_intermediate, rest_advanced',
  ') VALUES',
]

const rows = EXERCISES.map((ex, i) => {
  const isLast = i === EXERCISES.length - 1
  const instructionsArr = pgArray(ex.instructions)
  return [
    `  (`,
    `    ${pgText(ex.id)}, ${pgText(ex.name)}, ${pgText(ex.nameEs)},`,
    `    ${pgText(ex.muscleGroup)}, ${pgText(ex.muscleTarget)},`,
    `    ${pgArray(ex.primaryMuscles)}, ${pgArray(ex.secondaryMuscles)}, ${pgArray(ex.equipment)},`,
    `    ${ex.difficulty}, ${pgText(ex.type)}, ${ex.compoundBonus}, ${ex.image ? pgText(ex.image) : 'NULL'},`,
    `    ${instructionsArr},`,
    `    ${pgText(ex.sets.beginner)}, ${pgText(ex.sets.intermediate)}, ${pgText(ex.sets.advanced)},`,
    `    ${pgText(ex.reps.beginner)}, ${pgText(ex.reps.intermediate)}, ${pgText(ex.reps.advanced)},`,
    `    ${ex.rest.beginner}, ${ex.rest.intermediate}, ${ex.rest.advanced}`,
    `  )${isLast ? '' : ','}`,
  ].join('\n')
})

lines.push(...rows)
lines.push(';')
lines.push('')
lines.push(`-- Total: ${EXERCISES.length} exercises`)

console.log(lines.join('\n'))
